// Rescued from the game files, originally part of Black Pits 2
// Rebalancing and corrections by jmerry, first demonstrated on the Beamdog forums
// Only one original string; all others are in the game already

BEGIN ~J8#NOOB~

IF ~  Global("j8noober","GLOBAL",2)
~ THEN BEGIN 0 // from: 2.0
  SAY #100796 /* ~Heya! Wanna play a game?~ */
  IF ~~ THEN REPLY #100797 /* ~Yes!~ */ GOTO 3
  IF ~~ THEN REPLY #100798 /* ~Yes.~ */ GOTO 3
  IF ~~ THEN REPLY #100799 /* ~Yes?~ */ GOTO 3
  IF ~~ THEN REPLY #100800 /* ~No.~ */ GOTO 1
  IF ~~ THEN REPLY #100801 /* ~No. Gods, no.~ */ GOTO 1
END

IF ~~ THEN BEGIN 1 // from: 0.3 0.4 1.1 2.1 2.2
  SAY #101270 /* ~How about now?~ */
  IF ~~ THEN REPLY #101285 /* ~All right.~ */ GOTO 3
  IF ~~ THEN REPLY #100800 /* ~No.~ */ GOTO 1
  IF ~~ THEN REPLY #101286 /* ~No. No, no, no. Noooo...~ */ GOTO 2
END

IF ~~ THEN BEGIN 2 // from: 1.2
  SAY #101270 /* ~How about now?~ */
  IF ~~ THEN REPLY #101287 /* ~Yes. Fine. Let's play a game.~ */ GOTO 0
  IF ~~ THEN REPLY #101288 /* ~Please. No.~ */ GOTO 1
  IF ~~ THEN REPLY #101289 /* ~NO!~ */ GOTO 1
END

IF ~~ THEN BEGIN 3 // from: 0.0 0.1 0.2 1.0
  SAY #101271 /* ~How about now? Still wanna play a game?~ */
  IF ~~ THEN REPLY #101272 /* ~Yes!~ */ GOTO 4
  IF ~~ THEN REPLY #101273 /* ~I said yes.~ */ GOTO 4
END

IF ~~ THEN BEGIN 4 // from: 3.0 3.1
  SAY #101270 /* ~How about now?~ */
  IF ~~ THEN REPLY #101274 /* ~Still yes.~ */ GOTO 5
  IF ~~ THEN REPLY #101275 /* ~Can you hear me? I said yes.~ */ GOTO 5
END

IF ~~ THEN BEGIN 5 // from: 4.0 4.1
  SAY #101270 /* ~How about now?~ */
  IF ~~ THEN REPLY #101276 /* ~Yes, yes, I get it. Move on.~ */ GOTO 6
  IF ~~ THEN REPLY #101277 /* ~I'm going to kill you if you don't move forward.~ */ GOTO 6
END

IF ~~ THEN BEGIN 6 // from: 5.0 5.1
  SAY #101278 /* ~Great! We're gonna play a really fun game. But you gotta do some roleplaying! What do you wanna play as: a fighter, a wizard, or a thief?~ */
  IF ~~ THEN REPLY #101279 /* ~I shall take on the role of a fighter.~ */ GOTO 7
  IF ~~ THEN REPLY #101280 /* ~A wizard sounds like fun.~ */ GOTO 8
  IF ~~ THEN REPLY #101281 /* ~I enjoy sneaking around. Let me try being a thief.~ */ GOTO 9
END

IF ~~ THEN BEGIN 7 // from: 6.0
  SAY #101282 /* ~A fighter's a fine choice for your first game. I'm gonna be the dungeon master, which means I create the story and situations and then you get to play through them! I'll even roll your dice for you. Ready to play? Good, let's go.~ */
  IF ~~ THEN GOTO 10
END

IF ~~ THEN BEGIN 8 // from: 6.1
  SAY #101283 /* ~Ah, a fan of magic. Wizard it is, then. I'm gonna be the dungeon master, which means I create the story and situations and then you get to play through them! I'll even roll your dice for you. Ready to play? Good, let's go.~ */
  IF ~~ THEN GOTO 180
END

IF ~~ THEN BEGIN 9 // from: 6.2
  SAY #101284 /* ~Okay, thief it is! I'm gonna be the dungeon master, which means I create the story and situations and then you get to play through them! I'll even roll your dice for you. Ready to play? Good, let's go.~ */
  IF ~~ THEN GOTO 257
END

IF ~~ THEN BEGIN 10 // from: 7.0 327.0
  SAY #100803 /* ~Ooh, a fighter! You like to act tough, do you? I thought I wanted to be a fighter once, but then my mother reminded me I have trouble chopping wood for the winter... and the wood's sitting still! Better I stick to telling stories, I think.~ */
  IF ~~ THEN GOTO 11
END

IF ~~ THEN BEGIN 11 // from: 10.0
  SAY #100804 /* ~Anyway, let me just get my Tome of Adventure here... right, got it. Let's get started.~ */
  IF ~~ THEN GOTO 12
END

IF ~~ THEN BEGIN 12 // from: 11.0
  SAY #100805 /* ~You are a fighting <PRO_MANWOMAN>, a mercenary who makes <PRO_HISHER> living with <PRO_HISHER> sword, and a good living it has been. A paragon of youth, strength, and vitality, you are an impressive sight in your brightly polished armor. So it is no surprise that when you enter the town of Berenford, the children look at you in awe, even as their parents run to shield them from an unknown, yet powerful new presence.~ */
  IF ~~ THEN GOTO 13
END

IF ~~ THEN BEGIN 13 // from: 12.0
  SAY #100806 /* ~It is a day like any other, and you had briefly considered scrounging around Berenford for work, but something in these people's attitudes stops you in your tracks. All is not right here. It is not unusual for people to be scared of the unknown, but this group seems a bit TOO scared. As the adults shuffle their children indoors, you are left facing what might loosely be termed a town square. Looking around, you notice several nondescript buildings, a temple of Lathander, and a blacksmith.~ */
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100807 /* ~Enter the Temple of Lathander.~ */ GOTO 14
  IF ~  !Global("OHBN_SENESCHAL","LOCALS",1)
~ THEN REPLY #100808 /* ~Enter the blacksmith's.~ */ GOTO 20
END

IF ~~ THEN BEGIN 14 // from: 13.0 20.1 21.1 26.1 27.1 32.0
  SAY #100809 /* ~The Temple of Lathander is adorned in rich yellow, orange, and red tapestries arranged on the walls such that they mimic the hues and patterns of a rising sun. You at first think the temple to be empty before a small woman meekly pokes her head out of one of the side vestibules. "Sorry," she says timidly, "but I'm afraid the temple is closed. Please try back later."~ */
  IF ~~ THEN REPLY #100810 /* ~Ask her why the temple is closed.~ */ GOTO 15
  IF ~  !Global("OHBN_SENESCHAL","LOCALS",1)
~ THEN REPLY #100811 /* ~Leave the temple and enter the blacksmith's.~ */ GOTO 20
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100812 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 15 // from: 14.0
  SAY #100813 /* ~"The priest, Morninglord Aldaron, is not here at the moment, and I am but a lowly acolyte. I have neither the training nor enough of the Morninglord's favor to provide adequate temple services on my own."~ */
  IF ~~ THEN REPLY #100814 /* ~Inquire as to when Aldaron will return.~ */ GOTO 16
  IF ~  !Global("OHBN_SENESCHAL","LOCALS",1)
~ THEN REPLY #100815 /* ~Leave the temple and enter the blacksmith's.~ */ GOTO 20
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100816 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 16 // from: 15.0
  SAY #100817 /* ~"He does not approve his schedule with me," she answers curtly as she turns away. Yet something stops her, and she turns back, eyes your glistening armor and the heavy sword sheathed on your belt, and begins again. "I apologize, but the truth is the Morninglord has been gone too long now. He is almost certainly dead."~ */
  IF ~~ THEN GOTO 17
END

IF ~~ THEN BEGIN 17 // from: 16.0
  SAY #100818 /* ~"He left almost three tendays ago to journey to Mount Redigar, but he should have returned long ago. It is at most a three-day journey there and another three back. You can even see the mountain from the town square."~ */
  IF ~~ THEN GOTO 18
END

IF ~~ THEN BEGIN 18 // from: 17.0
  SAY #100819 /* ~"Mount Redigar is the home of Fernault, a warlord that recently moved into the area and began terrorizing the people. Aldaron was certain he could talk sense into the tyrant—confident that Lathander would protect him if the worst came—but he has not returned!"~ */
  IF ~~ THEN DO ~SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ GOTO 19
END

IF ~~ THEN BEGIN 19 // from: 18.0
  SAY #100820 /* ~"My mentor—my friend—has been slain by that monster, and now I don't see how the people here will ever be free of him! Please, <PRO_SIRMAAM>, you look to be a great warrior. Rid our town of this tyrant if you can! Oh, I'm sorry, but my emotions overwhelm me. I cannot speak any more of it!" She runs off, leaving you alone in the temple.~ */
  IF ~  !Global("OHBN_SENESCHAL","LOCALS",1)
~ THEN REPLY #100821 /* ~Leave the temple and enter the blacksmith's.~ */ GOTO 20
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100822 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 20 // from: 13.1 14.1 15.1 19.0
  SAY #100823 /* ~The blacksmith's shop is a small wooden building with a low roof and a crowded and drafty interior. The wall is lined with examples of his handiwork: swords, spears, and shields, but everything is covered in soot. The smith looks up warily from his anvil as you enter and beckons you forward. "What d'ya want?" he asks gruffly.~ */
  IF ~~ THEN REPLY #100824 /* ~Ask if he has anything rare for sale.~ */ GOTO 21
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100825 /* ~Leave the blacksmith's and enter the temple.~ */ GOTO 14
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100826 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 21 // from: 20.0
  SAY #100827 /* ~He shakes his head. "I have nothing for sale. Not anymore!"~ */
  IF ~~ THEN REPLY #100828 /* ~Ask why a merchant would have no items for sale.~ */ GOTO 22
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100829 /* ~Leave the blacksmith's and enter the temple.~ */ GOTO 14
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100830 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 22 // from: 21.0
  SAY #100831 /* ~"Because we no longer have any currency! All we used to have went to our new lord, Fernault. 'Taxes,' he called it, but it's more like 'theft' if you ask me! Because he simply takes everything we get, gold has become worthless here, and so I don't want any you may have. The only way I work now is for an exchange of services, and I doubt you'd have anything I want. Although..."~ */
  IF ~~ THEN GOTO 23
END

IF ~~ THEN BEGIN 23 // from: 22.0
  SAY #100832 /* ~Suddenly, there is a commotion at the door, and before you can object, the smith hurries you behind a nearby pile of crates and motions you to be silent. Almost before he can turn back around, a large man bursts into his shop. "Smith!" he bellows. "Your shipment is late. Where are the weapons Fernault has ordered?"~ */
  IF ~~ THEN DO ~SetGlobal("OHBN_SENESCHAL","LOCALS",1)
~ GOTO 24
END

IF ~~ THEN BEGIN 24 // from: 23.0
  SAY #100833 /* ~"I—I—I need time," the smith stammers in reply. "That many weapons cannot be made in a tenday, particularly when it is so difficult to come by supplies, a situation brought about by your master, I might add!"~ */
  IF ~~ THEN GOTO 25
END

IF ~~ THEN BEGIN 25 // from: 24.0
  SAY #100834 /* ~The large man steps forward and backhands the smith, sending him to the ground. "Watch your tongue, cur! First, Lord Fernault is not just MY master, but OUR master! Second, he will not be blamed for your incompetence! You have two days to finish the order. If you do not have the weapons by then, your daughter will pay the price!"~ */
  IF ~~ THEN REPLY #100835 /* ~Stay in hiding.~ */ GOTO 26
  IF ~~ THEN REPLY #100836 /* ~Smite the man from behind with your sword.~ */ GOTO 27
END

IF ~~ THEN BEGIN 26 // from: 25.0
  SAY #100837 /* ~The smith nods his understanding, and the large man barrels his way out the door. When he is gone, the smith motions you forward and out the door. "You've got to go," he says nervously. "I have far too much work to do."~ */
  IF ~~ THEN REPLY #100838 /* ~Ask him about Lord Fernault.~ */ GOTO 28
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100839 /* ~Leave the blacksmith's and enter the temple.~ */ GOTO 14
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100840 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 27 // from: 25.1
  SAY #100841 /* ~With a mighty swing, you split the man's skull, felling him in one blow. As his body slumps to the floor, the smith looks at you in a disbelief which soon turns to panic. "You've really done it now," he cries. "Lord Fernault's seneschal killed in my shop! Quick, help me get the body into the furnace before anyone finds it!"~ */
  IF ~~ THEN REPLY #100842 /* ~Ask him about Lord Fernault.~ */ GOTO 28
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100843 /* ~Leave the blacksmith's and enter the temple.~ */ GOTO 14
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100844 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 28 // from: 26.0 27.0
  SAY #100845 /* ~"No one's ever seen him," the man whispers, "but he and his soldiers came here several tendays ago and immediately set about robbing the people blind. Anything of value—gold, jewels, iron, even food and, as you just saw, weapons—they simply seize without payment."~ */
  IF ~~ THEN GOTO 29
END

IF ~~ THEN BEGIN 29 // from: 28.0
  SAY #100846 /* ~"His fortress lies somewhere in Mount Redigar to the north. That's where they took my daughter several days ago as a means of 'persuading' me to continue working for free. Why do you ask? You aren't really thinking of getting rid of him, are you? Because if you are, I beg you to keep an eye out for Peldea, my daughter. Rescue her if you can!"~ */
  IF ~~ THEN REPLY #100847 /* ~Agree to rescue his daughter.~ */ GOTO 30
  IF ~~ THEN REPLY #100848 /* ~Tell him that you cannot guarantee you will be able to rescue his daughter.~ */ GOTO 33
  IF ~~ THEN REPLY #100849 /* ~Tell him that you have no intention of going to Lord Fernault's fortress.~ */ GOTO 34
END

IF ~~ THEN BEGIN 30 // from: 29.0
  SAY #100850 /* ~"Oh, thank you!" he replies with a wide smile. "Since you have promised to return to me the only thing in this world I care about, I shall give you this!" He pulls up a loose plank from the floor, reaches his hand into the hole, and brings forth a rough cloth, which he quickly unwraps to reveal a perfectly smooth blue blade.~ */
  IF ~~ THEN GOTO 31
END

IF ~~ THEN BEGIN 31 // from: 30.0
  SAY #100851 /* ~As your hand grasps the sword's hilt, a series of orange runes pulse along the crossguard, hinting at the power within the blade. "It's called Caelfor, and it was passed to me by my father, a master smith known far and wide as the best these parts have ever known. I reckon there are few better swords in the world than this. May it always strike true for you, and if you could lodge it in Lord Fernault's brain, I would celebrate your name forever."~ */
  IF ~~ THEN DO ~SetGlobal("OHBN_BLADE","LOCALS",1)
~ GOTO 32
END

IF ~~ THEN BEGIN 32 // from: 31.0 33.0 34.0
  SAY #100852 /* ~"But we have spoken too long already. I really do need to get back to work, so I wish you luck in your travels. Farewell."~ */
  IF ~  !Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100853 /* ~Leave the blacksmith's and enter the temple.~ */ GOTO 14
  IF ~  Global("OHBN_KNOWS_FERNAULT","LOCALS",1)
~ THEN REPLY #100854 /* ~Leave the town and head to Mount Redigar.~ */ GOTO 35
END

IF ~~ THEN BEGIN 33 // from: 29.1
  SAY #100855 /* ~"Ah," he replies, obviously disappointed. "I shouldn't have gotten my hopes up. Suffice it to say, I will be happy for anything you can do."~ */
  IF ~~ THEN GOTO 32
END

IF ~~ THEN BEGIN 34 // from: 29.2
  SAY #100856 /* ~"Ah," he replies, obviously disappointed. "I shouldn't have gotten my hopes up. If you do change your mind, the people around here would be mightily relieved if you could end his tyranny."~ */
  IF ~~ THEN GOTO 32
END

IF ~~ THEN BEGIN 35 // from: 14.2 15.2 19.1 20.2 21.2 26.2 27.2 32.1
  SAY #100857 /* ~As you turn to the north, heading out of town, a short, balding man approaches you meekly, hat in hand. "Excuse me, <PRO_SIRMAAM>," he begins, "but you look as though you are made of the stuff of heroes. Would you free our town from the clutches of Lord Fernault and his soldiers?"~ */
  IF ~~ THEN REPLY #100858 /* ~Indicate that you will.~ */ GOTO 36
  IF ~~ THEN REPLY #100859 /* ~Say that you will for the right price.~ */ GOTO 37
  IF ~~ THEN REPLY #100860 /* ~Say that you are too busy at the moment.~ */ GOTO 38
END

IF ~~ THEN BEGIN 36 // from: 35.0
  SAY #100861 /* ~"Oh, thank you, THANK YOU!" He shakes your hand furiously. "We do not have anything to pay you with right now, for Fernault's greed is so great that he has stripped our land bare of anything of value. However, anyone that can storm his fortress and kill him will undoubtedly find his vaults filled to overflowing with gold. Now good luck to you, and fare thee well!"~ */
  IF ~~ THEN GOTO 39
END

IF ~~ THEN BEGIN 37 // from: 35.1
  SAY #100862 /* ~"We do not have anything to pay you with right now," he answers, "for Fernault's greed is so great that he has stripped our land bare of anything of value. However, anyone that can storm his fortress and kill him will undoubtedly find his vaults filled to overflowing with gold. But if that is not enough, then so be it. Fare thee well!"~ */
  IF ~~ THEN GOTO 39
END

IF ~~ THEN BEGIN 38 // from: 35.2
  SAY #100863 /* ~"That is a shame," he answers, "for Fernault's greed is so great that he has stripped our land bare of anything of value. Therefore, anyone that can storm his fortress and kill him will undoubtedly find his vaults filled to overflowing with gold. But if you are too busy, then so be it. Fare thee well!"~ */
  IF ~~ THEN GOTO 39
END

IF ~~ THEN BEGIN 39 // from: 36.0 37.0 38.0
  SAY #100864 /* ~"The soldiers were fighting amongst themselves, so they agreed to split up. One group took our wagon and horses and headed west. Another took my mother and brother and headed east." You look on the ground and, sure enough, there are tracks leading both east and west. The soldiers made no attempt to conceal their movement, so both paths would be easy enough to follow.~ */
  IF ~~ THEN REPLY #100865 /* ~Head west in pursuit of the wagon and horses.~ */ GOTO 40
  IF ~~ THEN REPLY #100866 /* ~Head east in pursuit of the girl's mother and brother.~ */ GOTO 57
  IF ~~ THEN REPLY #100867 /* ~Forget the entire mess and continue north towards Mount Redigar.~ */ DO ~SetGlobal("OHBN_HEARTLESS","LOCALS",1)
~ GOTO 69
END

IF ~~ THEN BEGIN 40 // from: 39.0
  SAY #100868 /* ~The path west winds around several low hills and into a lightly forested area. The sun filters down through the canopy, and the birds chirp merrily in the cool breeze. Overall, it is a not unpleasant journey.~ */
  IF ~~ THEN GOTO 41
END

IF ~~ THEN BEGIN 41 // from: 40.0
  SAY #100869 /* ~The sound of horses neighing is the first sign you have that you have caught your prey. You creep to the top of a small hill to find the wagon and two horses in the vale below. Two orcs talk animatedly with one another, although they do not seem to be fighting, and they regularly draw drinks from one of the casks on the wagon into their clay tankards, downing the frothy brew in single gulps before pouring again.~ CORRECTED */
  IF ~~ THEN REPLY #100870 /* ~Attack the orcs.~ */ GOTO 42
  IF ~~ THEN REPLY #100871 /* ~Settle down to wait for a better opportunity.~ */ GOTO 55
  IF ~~ THEN REPLY #100872 /* ~Leave the scene and continue north to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 42 // from: 41.0
  SAY #100873 /* ~You draw your blade and charge into the camp while the confused orcs drop their mugs and stumble for their weapons. Not giving them any chance to recover, you bring your sword down with a mighty blow, nearly cleaving the first orc in two, and then turn to face the second. The monster raises its axe and growls at you as it lumbers forward.~ */
  IF ~ RandomNumLT(6,3)
OR(2)
RandomNumLT(6,2)
!GLOBAL("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 44
  IF ~  RandomNumGT(6,1)
OR(2)
RandomNumGT(6,2)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 43
END

IF ~~ THEN BEGIN 43 // from: 42.1 42.2
  SAY #100874 /* ~You deftly sidestep the awkward swing and bring your own sword up in a backward arc directly into the orc's back. The blade cleaves through the monster's thin leather armor, and it grunts loudly as it falls over into the dust. It twitches a couple times on the ground but quickly stills in the blood-soaked mud.~ */
  IF ~~ THEN GOTO 46
END

IF ~~ THEN BEGIN 44 // from: 42.0
  SAY #100875 /* ~You deftly sidestep the awkward swing and bring your own sword up in a backward arc directly towards the orc's back, but you are surprised when the beast, anticipating your move, dives forward into the dirt, causing your own sword to swing harmlessly through the air.~ */
  IF ~~ THEN GOTO 45
END

IF ~~ THEN BEGIN 45 // from: 44.0
  SAY #100876 /* ~Before you can adjust, the orc swipes your legs out from under you, and your blade flies from your grip as you plunge headlong into the dirt. As you roll over, desperately trying to regain your footing, the orc lands on your chest, a dagger now plunging towards your throat. Within seconds, the world goes black.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 46 // from: 43.0 56.0
  SAY #100877 /* ~The sudden sound of soft chanting on the breeze makes the hair on the back of your neck stand on end. Turning around, you notice another orc you had not seen before, this one wearing the robes of a tribal shaman, standing by the wagon waving his hands.~ */
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100878 /* ~Charge him and attack.~ */ GOTO 49
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100878 /* ~Charge him and attack.~ */ GOTO 47
  IF ~~ THEN REPLY #100879 /* ~Throw your sword at him.~ */ GOTO 50
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100880 /* ~Run for cover.~ */ GOTO 52
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100880 /* ~Run for cover.~ */ GOTO 51
END

IF ~~ THEN BEGIN 47 // from: 46.1
  SAY #100881 /* ~You quickly cover the ground between the two of you, but not before the shaman finishes his enchantment. You notice a shimmering in the air around his hands that quickly enlarges to encompass you. For a moment, you feel extremely tired, and you find yourself thinking of simply curling up on the ground and going to sleep, but you manage to shake off the effects of the enchantment.~ */
  IF ~~ THEN GOTO 48
END

IF ~~ THEN BEGIN 48 // from: 47.0 50.0 51.0
  SAY #100882 /* ~With a mighty roar, you raise your sword and bring it down upon the upraised arm of the shaman. Skin and bone give way as you slice clean through the frail body. The orc crumples to the ground and moves no more.~ */
  IF ~~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",1)
~ GOTO 53
END

IF ~~ THEN BEGIN 49 // from: 46.0
  SAY #100883 /* ~You quickly cover the ground between the two of you, but not before the shaman finishes his enchantment. You notice a shimmering in the air around his hands that quickly enlarges to encompass you. Suddenly, you feel extremely tired, and you find yourself thinking how wonderful a nap would feel. Without a care in the world, you curl up into a ball and fade off into a dream from which you never wake.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 50 // from: 46.2
  SAY #100884 /* ~With a shout, you hurl your sword through the air. The weapon arcs wildly and clatters noisily into the wagon, but it is enough to disrupt the shaman's concentration. His spell fizzles with a sharp explosion, and he staggers back, hands already digging into his pouches for another set of reagents. Acting quickly, you give him a swift punch to his jaw that sends him reeling. You regain your sword as he begins weaving another spell.~ */
  IF ~~ THEN GOTO 48
END

IF ~~ THEN BEGIN 51 // from: 46.4
  SAY #100885 /* ~You quickly dodge behind the wagon, but not before the shaman finishes his enchantment. You notice a shimmering in the air around his hands that quickly enlarges to encompass you. For a moment, you feel extremely tired, and you find yourself thinking of simply curling up on the ground and going to sleep, but you manage to shake off the effects of the enchantment. Realizing his spell has failed, you charge around the wagon and straight for him.~ */
  IF ~~ THEN GOTO 48
END

IF ~~ THEN BEGIN 52 // from: 46.3
  SAY #100886 /* ~You quickly dodge behind the wagon, but not before the shaman finishes his enchantment. You notice a shimmering in the air around his hands that quickly enlarges to encompass you. Suddenly, you feel extremely tired, and you find yourself thinking how wonderful a nap would feel. Without a care in the world, you curl up into a ball and fade off into a dream from which you never wake.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 53 // from: 48.0
  SAY #100887 /* ~Searching the wagon reveals little of use to you. The cargo consists mostly of the drained ale kegs, bolts of cloth, beads, and other baubles for making clothes, but one helmet draws your attention. Though it is made of metal and appears well crafted and sturdy, it is very light—too light for normal metal. A set of soft purple runes etched into the crown confirms that the helmet is enchanted in some way.~ */
  IF ~~ THEN REPLY #100888 /* ~Put the helmet on.~ */ DO ~SetGlobal("OHBN_HELMET","LOCALS",1)
~ GOTO 54
  IF ~~ THEN REPLY #100889 /* ~Discard the helmet and continue on to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 54 // from: 53.0
  SAY #100890 /* ~The helm fits easily onto your head—so easily, in fact, that you swear it must have been forged just for you—but you experience no obvious magical effect. Shrugging, you proceed onwards towards Mount Redigar.~ */
  IF ~~ THEN GOTO 69
END

IF ~~ THEN BEGIN 55 // from: 41.1
  SAY #100891 /* ~You settle down to observe the camp. Hours go by until night at last settles over the scene. Although the two orcs occasionally gaze out into the fields to the south—thereby hinting at the existence of others out foraging for food or supplies—no one else returns to the camp. At last, the ale gets the best of the two, and they settle down by the fire, the sounds of snoring soon filling the air.~ */
  IF ~~ THEN REPLY #100892 /* ~Sneak up on the orcs and kill them.~ */ GOTO 56
  IF ~~ THEN REPLY #100893 /* ~Leave the scene and continue north to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 56 // from: 55.0
  SAY #100894 /* ~You sneak up quietly and plunge your sword into the first orc's gut. The beast squeals under the blow but otherwise is unable to react before its life bleeds out. The second orc sits up with a shout, but you bring your blade up in a savage arc directly into its jaw. It too slumps over in a pool of its own blood. The entire fight is finished before it has begun.~ */
  IF ~~ THEN GOTO 46
END

IF ~~ THEN BEGIN 57 // from: 39.1
  SAY #100895 /* ~The path east winds around several low hills and into a lightly forested area. The sun filters down through the canopy, and the birds chirp merrily in the cool breeze. Overall, it is a not unpleasant journey.~ */
  IF ~~ THEN GOTO 58
END

IF ~~ THEN BEGIN 58 // from: 57.0
  SAY #100896 /* ~As the light fades, you come to a break in the trees that harbors a small camp. Within, a single large humanoid figure absently pokes a stick into a fire pit while two frightened humans—a woman and a young boy—sit opposite, wide-eyed with fear.~ */
  IF ~~ THEN GOTO 59
END

IF ~~ THEN BEGIN 59 // from: 58.0
  SAY #100897 /* ~The large humanoid shifts position so that you can clearly see its face, and your initial suspicion is confirmed. It is an ogre, the smallest and weakest of the giant-kin, but nevertheless much larger and stronger than a human. Looking around, you see no other guards for the two prisoners. The ogre sighs and continues poking his stick into the fire disinterestedly.~ */
  IF ~~ THEN REPLY #100898 /* ~Sneak up behind the ogre and attack him.~ */ GOTO 60
  IF ~~ THEN REPLY #100899 /* ~Wait for a better opportunity.~ */ GOTO 66
  IF ~~ THEN REPLY #100900 /* ~Leave the captives to their fate and continue to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 60 // from: 59.0
  SAY #100901 /* ~You tiptoe silently up behind the ogre, but a misstep causes a twig to break loudly under your feet. The ogre snaps to attention and turns quickly around. It snarls at the sight of you and picks up the bone of a large unknown animal lying nearby. Swinging its bone club with a roar, it lumbers towards you.~ */
  IF ~  RandomNumLT(6,5)
OR(2)
RandomNumLT(6,4)
!GLOBAL("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #100902 /* ~Stand and fight the ogre.~ */ GOTO 65
  IF ~  RandomNumGT(6,3)
OR(2)
RandomNumGT(6,4)
GLOBAL("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #100902 /* ~Stand and fight the ogre.~ */ GOTO 61
  IF ~~ THEN REPLY #100903 /* ~Flee and continue to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 61 // from: 60.1 67.1
  SAY #100904 /* ~The ogre swings its makeshift club wildly at you as you deftly feint to the right and then dodge left. Your move puts the behemoth off balance, and you seize the opportunity to swing your sword into its unprotected right flank. You feel the crack of ribs as your sword bites deep into its side, and the ogre emits a howl of pain and rage.~ */
  IF ~~ THEN GOTO 62
END

IF ~~ THEN BEGIN 62 // from: 61.0
  SAY #100905 /* ~The monster again swings wildly, but you nimbly duck and counter with a thrust up under its crude breastplate and into its soft underbelly. The beast drops its club in surprise and grasps its stomach, desperately trying to keep its entrails from spilling out. It looks at you first in surprise and then horror as it stumbles backwards and collapses into the fire pit.~ CORRECTED */
  IF ~~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",1)
~ GOTO 63
END

IF ~~ THEN BEGIN 63 // from: 62.0
  SAY #100906 /* ~You quickly untie the two prisoners and usher them into the woods, but the female prisoner resists and instead approaches the ogre's burnt body. She rifles through the beast's pouches and pulls forth a small, nondescript silver ring, which she then hands to you. "My husband is dead and so will no longer need this," she says sadly, "but the service you have done me today deserves a reward. When you wear this ring, you will become completely invisible to everyone else."~ */
  IF ~~ THEN DO ~SetGlobal("OHBN_RING","LOCALS",1)
~ GOTO 64
END

IF ~~ THEN BEGIN 64 // from: 63.0 68.0
  SAY #100907 /* ~You escort the two former prisoners back to the site of the attack and the young girl still hiding in the grass. The small group again mourns their dead but thanks you for reuniting those that are left. The three depart on foot towards Berenford to the south, and you are left to continue traveling north towards Mount Redigar.~ */
  IF ~~ THEN GOTO 69
END

IF ~~ THEN BEGIN 65 // from: 60.0 67.0
  SAY #100908 /* ~The ogre swings its makeshift club as you feint to the right and then attempt to dodge back left, but the cagey beast deftly reverses its swing to catch you right in the gut. You stagger backwards as the air knocked out of you, but the ogre closes quickly, its bone club already raised for another blow. You raise your sword desperately to parry, but the next swing forces you to the ground and knocks the blade from your hand. You look up in time to see the third blow raining down. It is the last sight you ever see.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 66 // from: 59.1
  SAY #100909 /* ~You hunch down into the tall grass to observe the ogre and wait for a better opportunity. Every so often, the beast stops poking the fire long enough to look around—thereby hinting at the existence of others out foraging for food or supplies—but none ever return. At last, long after night has settled over the camp, the ogre slumps down and closes its eyes. A few minutes later, you hear the unmistakable sound of snoring.~ */
  IF ~~ THEN REPLY #100910 /* ~Sneak up on the beast and kill it.~ */ GOTO 67
  IF ~~ THEN REPLY #100911 /* ~Sneak around to the prisoners and free them.~ */ GOTO 68
  IF ~~ THEN REPLY #100912 /* ~Leave the captives to their fate and continue to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 67 // from: 66.0
  SAY #100913 /* ~You tiptoe silently up to the ogre, but a misstep causes a twig to snap loudly under your feet. The monster's eyes fly open as it jumps to attention and turns around. It snarls at the sight of you, leaps up with surprising agility, and picks up the bone of a large unknown animal lying nearby. Swinging its bone club with a roar, it lumbers towards you.~ */
  IF ~  RandomNumLT(6,5)
OR(2)
RandomNumLT(6,4)
!GLOBAL("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #100914 /* ~Stand and fight the ogre.~ */ GOTO 65
  IF ~  RandomNumGT(6,3)
OR(2)
RandomNumGT(6,4)
GLOBAL("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #100914 /* ~Stand and fight the ogre.~ */ GOTO 61
  IF ~~ THEN REPLY #100915 /* ~Flee and continue to Mount Redigar.~ */ GOTO 69
END

IF ~~ THEN BEGIN 68 // from: 66.1
  SAY #100916 /* ~Silently, you make your way to the two prisoners on the opposite side of the fire. They awaken as you approach, but you motion for them to be quiet as you slice through their bonds with your sword. Within moments, they are free.~ */
  IF ~~ THEN GOTO 64
END

IF ~~ THEN BEGIN 69 // from: 39.2 41.2 53.1 54.0 55.1 59.2 60.2 64.0 66.2 67.2
  SAY #100917 /* ~The path north is uneventful, and a quick encampment allows you to get a few hours' rest before continuing north in the early morning. Before long, you come upon a single traveler going in the opposite direction. He leans heavily on a walking stick, and his gray beard blends perfectly into his flowing robes. "Excuse me, <PRO_SIRMAAM>," he beckons to you, "You look to be a warrior of some skill. Would you, by chance, be traveling to see Lord Fernault at Mount Redigar?"~ */
  IF ~~ THEN REPLY #100918 /* ~Tell him you are going to rid the region of Lord Fernault.~ */ GOTO 70
  IF ~~ THEN REPLY #100919 /* ~Tell him you are going to try to join Lord Fernault's army.~ */ GOTO 71
  IF ~~ THEN REPLY #100920 /* ~Deny that you are going to Mount Redigar.~ */ GOTO 71
  IF ~~ THEN REPLY #100921 /* ~Ignore him and continue north to Mount Redigar.~ */ GOTO 74
END

IF ~~ THEN BEGIN 70 // from: 69.0
  SAY #100922 /* ~"Ah, I was right. You look just the type, and so I have a gift for you." From his pack, he takes a ragged gray cloak that looks to have been singed in a fire and hands it to you.~ */
  IF ~~ THEN REPLY #100923 /* ~Thank him and put the cloak on.~ */ GOTO 72
  IF ~~ THEN REPLY #100924 /* ~Ask him why you would want an old cloak.~ */ GOTO 73
  IF ~~ THEN REPLY #100925 /* ~Refuse the gift.~ */ GOTO 71
END

IF ~~ THEN BEGIN 71 // from: 69.1 69.2 70.2 73.1
  SAY #100926 /* ~"Ah, it seems I was wrong about you," he shrugs. "Sorry to bother you then." He whistles a light tune as he continues south, and you are left alone on the road north.~ */
  IF ~~ THEN GOTO 74
END

IF ~~ THEN BEGIN 72 // from: 70.0 73.0
  SAY #100927 /* ~The cloak is light, but amazingly sturdy given its decrepit appearance. You feel a slight warmth as you pull it around you, but it is otherwise unremarkable. The man smiles at you. "Keep that cloak with you when you meet Lord Fernault. You will need it," he says as he continues south. All other questions are met only with a shake of his head as he fades into the distance. You turn back to the road north.~ */
  IF ~~ THEN DO ~SetGlobal("OHBN_CLOAK","LOCALS",1)
~ GOTO 74
END

IF ~~ THEN BEGIN 73 // from: 70.1
  SAY #100928 /* ~"This cloak is certainly old," he begins, "but age is not always a reason to discard something. I know well that great power often comes with great age. I can guarantee you that Lord Fernault thinks the same way."~ */
  IF ~~ THEN REPLY #100929 /* ~Thank him and put the cloak on.~ */ GOTO 72
  IF ~~ THEN REPLY #100930 /* ~Refuse the gift.~ */ GOTO 71
END

IF ~~ THEN BEGIN 74 // from: 69.3 71.0 72.0
  SAY #100931 /* ~You travel north another day and spend another fitful night beneath the stars before at last reaching Redigar in the morning. The lonely mountain dominates the sky, and you can see a curl of smoke issuing forth from the summit. It doesn't take long for you to locate a cave entrance that is remarkably unguarded. You venture within.~ */
  IF ~~ THEN GOTO 75
END

IF ~~ THEN BEGIN 75 // from: 74.0
  SAY #100932 /* ~The torchlit passage slopes downwards for some way before evening out, and a breeze—warm, dry, and stifling—washes over you and causes the torchlight to dance playfully on the walls. From far away, you hear a strange, guttural barking in a tongue you do not understand, but you soon realize that it is, in fact, singing. The voice is rough, deep, and completely inhuman.~ */
  IF ~~ THEN GOTO 76
END

IF ~~ THEN BEGIN 76 // from: 75.0 100.0
  SAY #100933 /* ~The singing grows louder as you approach a doorway. Peeking around the edge, you see a crude kitchen with scattered tables holding a plethora of haphazard spices, foodstuffs, and cooking implements. A large fire pit dominates the center of the room, over which hangs a heavy boiling cauldron supported by an iron rod set between two massive oaken beams. A troll, humming a tuneless melody, uses a human femur to stir the contents.~ */
  IF ~~ THEN GOTO 77
END

IF ~~ THEN BEGIN 77 // from: 76.0
  SAY #100934 /* ~The passage leads onward past the doorway and further into the mountain. You also see a second passage out of the kitchen directly across from your position, although the troll lies between you and it.~ */
  IF ~~ THEN REPLY #100935 /* ~Continue further along the same passage.~ */ GOTO 99
  IF ~~ THEN REPLY #100936 /* ~Attack the troll.~ */ GOTO 78
  IF ~ !Global("OHBN_HEARTLESS","LOCALS",1)
~ THEN REPLY #100937 /* ~Try to sneak past the troll to the second passage.~ */ GOTO 97
  IF ~  Global("OHBN_HEARTLESS","LOCALS",1)
~ THEN REPLY #100937 /* ~Try to sneak past the troll to the second passage.~ */ GOTO 94
  IF ~ Global("OHBN_RING","LOCALS",1)
~ THEN REPLY #100938 /* ~Put on your ring of invisibility and walk past the troll to the second passage.~ */ GOTO 98
END

IF ~~ THEN BEGIN 78 // from: 77.1 91.0 94.0 95.0 96.0 97.0
  SAY #100939 /* ~You are upon the troll in a flash. Surprised, the monster turns and raises its arm in defense as your blade cleaves cleanly through the limb and bites deep into its chest. It staggers backward, howling terribly, and steadies itself against one of the great oaken beams.~ */
  IF ~~ THEN GOTO 79
END

IF ~~ THEN BEGIN 79 // from: 78.0
  SAY #100940 /* ~You move to continue the assault when you feel something grab your ankle. Looking down, you notice the arm you severed appears to have a life of its own, as it grabs at your feet and tries to trip you. You look up to see the troll smiling macabrely at you. As you watch, a new arm sprouts from the stump, and the massive wound you carved into its chest closes and heals. Within moments, the monster is whole again.~ */
  IF ~~ THEN REPLY #100941 /* ~Continue the attack with your sword.~ */ GOTO 80
  IF ~~ THEN REPLY #100942 /* ~Try to shake the severed arm off your foot.~ */ GOTO 83
  IF ~~ THEN REPLY #100943 /* ~Run away.~ */ GOTO 93
END

IF ~~ THEN BEGIN 80 // from: 79.0
  SAY #100944 /* ~The severed arm impedes you, but you fight through your reduced mobility, again bringing your sword down through an upstretched arm. This time, however, you press your advantage by reversing your swing and bringing your blade back up and clean through the creature's neck. Its head falls off its shoulders and rolls to a stop a few yards away as the body slumps to the ground.~ */
  IF ~~ THEN GOTO 81
END

IF ~~ THEN BEGIN 81 // from: 80.0
  SAY #100945 /* ~Yet even this does not seem to stop the creature. You watch in horror as the body reaches over with its remaining arm, grabs the head, and sets it back upon its shoulders, the bone, skin, and sinew quickly repairing before your eyes. You look down to find that both the severed arms are wrapped around your ankles, making movement now very difficult. You have mere seconds to determine a course of action that will save you.~ CORRECTED */
  IF ~~ THEN REPLY #100946 /* ~Hack the troll's head off with your sword again.~ */ GOTO 82
  IF ~~ THEN REPLY #100947 /* ~Try to shake the severed arm off your foot.~ */ GOTO 83
  IF ~~ THEN REPLY #100948 /* ~Run away.~ CORRECTED */ GOTO 93
END

IF ~~ THEN BEGIN 82 // from: 81.0 83.0 101.0
  SAY #100949 /* ~You raise your sword again for another strike, but before you can bring the blade down, the troll reaches up with its taloned hand, grabs you by the neck, and lifts you clean off the ground. You frantically stab at it as it hisses at you malevolently and slowly crushes your windpipe. Within moments, the world goes black as you fade into oblivion.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 83 // from: 79.1 81.1
  SAY #100950 /* ~You use your sword as a lever to pry the fingers from around your ankles and then shake your foot furiously to kick the severed arm away. The limb bounces on the floor a couple times before landing in the cooking fire with a loud pop. Suddenly, the troll emits the first true howl of pain you've heard from it, and the arm twitches in the flame for a brief time before finally shriveling to a black crisp and dissolving to ash.~ */
  IF ~~ THEN REPLY #100951 /* ~Continue to attack the troll with your sword.~ */ GOTO 82
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100952 /* ~Try to push the whole beast into the fire pit.~ */ GOTO 86
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100952 /* ~Try to push the whole beast into the fire pit.~ */ GOTO 84
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100953 /* ~Grab a torch from a wall sconce and use the makeshift club to attack the troll.~ */ GOTO 89
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100953 /* ~Grab a torch from a wall sconce and use the makeshift club to attack the troll.~ */ GOTO 87
  IF ~~ THEN REPLY #100954 /* ~Flee Mount Redigar and abandon the quest.~ */ GOTO 91
END

IF ~~ THEN BEGIN 84 // from: 83.2 91.2
  SAY #100955 /* ~You charge into the massive troll with your shoulder, attempting to muscle it into the fire. The beast instantly realizes your intent and grabs you by the waist with its muscular arm, attempting to lift you whole off the ground. You deftly wriggle out of its grasp, dive low, and grab its leg. Desperately, it claws at your back, but your mail performs its job perfectly, and you use your superior position to force the monster off balance and back into the cooking pit.~ */
  IF ~~ THEN GOTO 85
END

IF ~~ THEN BEGIN 85 // from: 84.0
  SAY #100956 /* ~The troll emits a howl that chills you to the bone, and its thrashing sends sparks and embers flying across the room. But its fate is sealed. Within seconds, the once-massive troll is little more than a pile of ash. You take a moment to collect both your bearings and your dropped gear and then proceed out the door opposite from where you entered.~ */
  IF ~~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",1)
~ GOTO 116
END

IF ~~ THEN BEGIN 86 // from: 83.1 91.1
  SAY #100957 /* ~You charge into the massive troll with your shoulder, attempting to muscle it into the pit. The beast instantly realizes your intent and grabs you by the waist with its muscular arm, attempting to lift you whole off the ground. You try to wriggle out of its grasp, but it proves surprisingly nimble. It picks you up and hurls you to the floor, knocking the wind out of you. Quickly, it closes the gap, its taloned hands clawing at your neck. It is the last sight you see in life.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 87 // from: 83.4 91.4 107.1
  SAY #100958 /* ~Seeing the flaming club in your hand, the troll loses courage and begins to slowly give way, its arms raised in front of its face in defense. You lunge forward, thrusting the torch like a sword under the defending limbs to score a direct hit on the beast's chest. It howls in pain and, realizing it has nowhere to run, finally moves to the attack, but you bring the club up in a backhanded swing and connect with its jaw.~ */
  IF ~~ THEN GOTO 88
END

IF ~~ THEN BEGIN 88 // from: 87.0 107.0
  SAY #100959 /* ~You decisively press your advantage, and the troll again cedes ground, only this time it trips on one of the many piles of debris and plunges to the floor. You move quickly on the beast, hitting it repeatedly with the flame as it howls in pain and tries to crawl away. Within moments, it is still, and you use the torch to light the entire body on fire. Soon, the once-massive troll is little more than a pile of ash. You take a moment to collect both your bearings and your dropped gear and then proceed out the door opposite from where you entered.~ */
  IF ~~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",1)
~ GOTO 116
END

IF ~~ THEN BEGIN 89 // from: 83.3 91.3
  SAY #100960 /* ~Seeing the flaming club in your hand, the troll loses courage and begins to slowly give way, its arms raised in front of its face in defense. You lunge forward, thrusting the club like a sword under the defending limbs to score a direct hit on the beast's chest. It howls in pain and, realizing it now has nothing to lose, finally moves to the attack. You bring the club up in a backhanded swing towards its face, but it catches the end of the flaming club in one of its massive hands.~ */
  IF ~~ THEN GOTO 90
END

IF ~~ THEN BEGIN 90 // from: 89.0
  SAY #100961 /* ~You feel the bone in the hand give way and smell the putrid scent of burning flesh, but you have no way of blocking the troll's other massive talon that connects cleanly with your jaw. The club flies from your hand as you stagger backwards, dazed. The monster loses no time in closing the gap, and its claws quickly close around your throat. Within moments, you have lost consciousness, never to wake again.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 91 // from: 83.5
  SAY #100962 /* ~Really? You run away? What kind of adventure is that, you coward? Time to reconsider.~ */
  IF ~~ THEN REPLY #100963 /* ~Continue to attack the troll with your sword.~ */ GOTO 78
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100964 /* ~Try to push the whole beast into the fire pit.~ */ GOTO 86
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100964 /* ~Try to push the whole beast into the fire pit.~ */ GOTO 84
  IF ~  RandomNumLT(6,5)
~ THEN REPLY #100965 /* ~Grab a torch from a wall sconce and use the makeshift club to attack the troll.~ */ GOTO 89
  IF ~  RandomNumGT(6,4)
~ THEN REPLY #100965 /* ~Grab a torch from a wall sconce and use the makeshift club to attack the troll.~ */ GOTO 87
END

IF ~~ THEN BEGIN 92 // from: 115.1 141.1 148.1
  SAY #100966 /* ~Fine then! Since that makes our game no fun, I think I'll exercise my dungeon master's prerogative and just say that as you're running away, a rabid goat jumps out of the woods and gores you to death. Now you're dead, so hah!~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 93 // from: 79.2 81.2
  SAY #100967 /* ~You turn to flee, but trip over the limb still attached to your ankle. You scramble to get back up, but the troll loses no time in closing the gap, and its claws quickly close around your throat. Within moments, you have lost consciousness, never to wake again.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 94 // from: 77.3
  SAY #100968 /* ~You wait for the troll to turn its back to you and then use the gloom of the firelit chamber to sneak to the other side. Yet when you are only halfway across, the troll raises its nose, sniffs the air, and then turns in delight. "You have returned!" it cackles. "Did you bring anything for the stew?"~ */
  IF ~~ THEN REPLY #100969 /* ~Attack the troll.~ */ GOTO 78
  IF ~~ THEN REPLY #100970 /* ~Answer that you did not.~ */ GOTO 95
  IF ~~ THEN REPLY #100971 /* ~Give it a portion of your rations.~ */ GOTO 96
END

IF ~~ THEN BEGIN 95 // from: 94.1
  SAY #100972 /* ~It looks at you with a mixture of disappointment and irritation. "You know how much I like different creatures for the stew! Is it too much to ask that when you go on patrol, you at least bring me a little something too? I can't believe how incompetent you lot are! Now begone, and be glad Lord Fernault has forbidden me to put his guards in my stew!"~ */
  IF ~~ THEN REPLY #100973 /* ~Attack the troll.~ */ GOTO 78
  IF ~~ THEN REPLY #100974 /* ~Move on to the passage opposite the one you entered.~ */ GOTO 116
END

IF ~~ THEN BEGIN 96 // from: 94.2
  SAY #100975 /* ~It gives something surprisingly close to a squeal of delight. "Oh, thank you! You know how much I like different creatures for the stew! I'm envious that you guards get to go on patrol, but at least you're good enough to bring me a little something when you do!" It plops the food into the stew and begins again humming its tuneless melody.~ */
  IF ~~ THEN REPLY #100976 /* ~Attack the troll.~ */ GOTO 78
  IF ~~ THEN REPLY #100977 /* ~Move on to the passage opposite the one you entered.~ */ GOTO 116
END

IF ~~ THEN BEGIN 97 // from: 77.2
  SAY #100978 /* ~You wait for the troll to turn its back to you and then use the gloom of the firelit chamber to sneak to the other side. Yet when you are only halfway across, the troll raises its nose, sniffs the air, and then turns in delight. "I thought I smelled dessert!" it cackles. Realizing your gambit has failed and you are now too exposed to turn back, you are forced to attack.~ */
  IF ~~ THEN GOTO 78
END

IF ~~ THEN BEGIN 98 // from: 77.4
  SAY #100979 /* ~You slip the ring on and quietly make your way through the chamber. When you are only halfway across, the troll raises its nose, sniffs the air, and then turns in delight. "I thought I smelled dessert!" it cackles, before its face turns to one of confusion. "Huh? Where are you?" it asks quizzically. It creeps past you to the tables behind you and begins searching through potential hiding spots. You realize you have the opportunity to escape, and you hurriedly move through the kitchen to the passage opposite.~ */
  IF ~~ THEN GOTO 116
END

IF ~~ THEN BEGIN 99 // from: 77.0
  SAY #100980 /* ~The passage descends a bit further, and before long you hear the sound of rough laughter. You slowly approach a doorway at the end of the hallway to see several human guards playing cards and drinking profusely. They joke raucously as they throw bits of meat or slugs of ale at each other and generally act like drunken degenerates. You see another exit further into the mountain directly across the room from you.~ */
  IF ~~ THEN REPLY #100981 /* ~Return back up the passage to the troll.~ */ GOTO 100
  IF ~~ THEN REPLY #100982 /* ~Attack the guards.~ */ GOTO 101
  IF ~  !Global("OHBN_HEARTLESS","LOCALS",1)
~ THEN REPLY #100983 /* ~Enter the room authoritatively and bluff your way past the guards.~ */ GOTO 112
  IF ~  Global("OHBN_HEARTLESS","LOCALS",1)
~ THEN REPLY #100983 /* ~Enter the room authoritatively and bluff your way past the guards.~ */ GOTO 110
  IF ~  Global("OHBN_RING","LOCALS",1)
~ THEN REPLY #100984 /* ~Put on your ring of invisibility and sneak past the guards.~ */ GOTO 114
END

IF ~~ THEN BEGIN 100 // from: 99.0
  SAY #100985 /* ~You turn and head back up the tunnel to your previous location. Soon, the sound of guttural singing has once more replaced that of raucous laughter.~ */
  IF ~~ THEN GOTO 76
END

IF ~~ THEN BEGIN 101 // from: 99.1 111.0 113.0
  SAY #100986 /* ~You draw your sword and pounce on the first guard with a single motion, cleaving deep into his chest and felling him before he can react. A second guard growls ferally at you and brings her mace around savagely. You easily parry her drunken swing, thrust your sword up under her ribcage, and then shove her gasping body backwards in a collapsing heap.~ */
  IF ~ RandomNumLT(6,4)
OR(2)
RandomNumLT(6,3)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 103
  IF ~  RandomNumGT(6,2)
OR(2)
RandomNumGT(6,3)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 102
END

IF ~~ THEN BEGIN 102 // from: 101.1
  SAY #100987 /* ~The third and fourth guards are upon you before she hits the ground, but you deftly position your body so that one has no room to get a full swing even as you parry the attack of the other and counter with a fierce blow to the neck. As he drops, you pivot, bringing your sword around in a powerful arc that sweeps through the feeble attempt to parry and cleaves deep into the fourth guard's side. He too stumbles backwards in a heap.~ */
  IF ~~ THEN GOTO 105
END

IF ~~ THEN BEGIN 103 // from: 
  SAY #100988 /* ~The third and fourth guards are upon you before she hits the ground, but you deftly position your body so that one has no room to get a full swing even as you parry the attack of the other and counter with a fierce blow to the neck. As he drops, you pivot, bringing your sword around in a powerful arc...~ */
  IF ~~ THEN GOTO 104
END

IF ~~ THEN BEGIN 104 // from: 103.0 109.0
  SAY #100989 /* ~...that sweeps through air only. The man had taken an unexpected step back, but now he rushes forward, thrusting his sword through one of the joints in your mail. You stumble backwards and look up just in time to see the second blow coming in clean to your neck. It is the last thing you see in this life.~ CORRECTED */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 105 // from: 102.0
  SAY #100990 /* ~With the guards defeated, you take a moment to catch your breath when a large figure steps out of the deep shadows of the torchlit room. The golden trim on his armor marks him as a soldier of some rank. "Congratulations," the gravelly baritone chides, "you managed to dispatch four drunkards." He slides his massive sword from its sheath and grips the handle easily in both hands. "Let's see if you can defeat a sober warrior, eh?"~ */
  IF ~~ THEN REPLY #100991 /* ~Attack the new warrior.~ */ GOTO 106
  IF ~~ THEN REPLY #100992 /* ~Flee Mount Redigar and abandon the quest.~ */ GOTO 115
END

IF ~~ THEN BEGIN 106 // from: 105.0 115.0
  SAY #100993 /* ~The man leaps at you, bringing his large blade around in a surprisingly tight arc. You parry the blow, but the force sends you staggering back, your hands ringing with the power of the collision. Yet you have no time to recover, for the man bears down again on you with a series of three rapid swings that you barely manage to avoid. You give ground and kick one of the overturned chairs into his path, a desperate gambit that gives you a scant amount of breathing room.~ */
  IF ~~ THEN GOTO 107
END

IF ~~ THEN BEGIN 107 // from: 106.0
  SAY #100994 /* ~Your opponent brings his sword down violently on the chair, smashing it easily to splinters, and disdainfully kicks the debris away. With surprisingly quick reflexes for a man wearing such heavy armor, he charges you, closing the distance in less than a second.~ */
  IF ~ RandomNumLT(6,5)
OR(2)
RandomNumLT(6,4)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 109
  IF ~  RandomNumGT(6,3)
OR(2)
RandomNumGT(6,4)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 108
END

IF ~~ THEN BEGIN 108 // from: 
  SAY #100995 /* ~Reflexively, you move to step back, but then instead dive forward, sweeping his feet from under him. The man falls in stunned disbelief at your unorthodox tactic, his sword clattering on the cave floor. In a flash, you regain your feet and swing your blade backhanded directly into his face guard, splitting his helmet and then his skull. He collapses with a thud. You give a brief look around the room at the now five corpses and proceed into the tunnel opposite the one you entered.~ */
  IF ~~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",1)
~ GOTO 116
END

IF ~~ THEN BEGIN 109 // from: 
  SAY #100996 /* ~Reflexively, you move to step back, desperately parrying the next rapid succession of blows. You marvel at the speed of the man's blade, given the size of his sword and the weight of his mail, and you know your chances to seize victory will be few. You step forward, hoping to come well within the killing arc of his sword and sweep your own blade upwards in a powerful arc of your own...~ */
  IF ~~ THEN GOTO 104
END

IF ~~ THEN BEGIN 110 // from: 99.3
  SAY #100997 /* ~As you step confidently into the room, the guards struggle to stand up, each giving a drunken approximation of either a bow or a salute. "Itsh about time you gotsh here!" one says. "How long doesh a patrol take?"~ */
  IF ~~ THEN GOTO 111
END

IF ~~ THEN BEGIN 111 // from: 110.0
  SAY #100998 /* ~A second chimes in, "Yeah, you know ol' Lord Funrault—hehe, I mean Fernault—wantsh hish gold, and he wantsh it when he wantsh it! Sho you besht getsh goin', and I hopesh you gotsh a lot out of all thosh peasants! Hehe!"~ */
  IF ~~ THEN REPLY #100999 /* ~Attack the guards.~ */ GOTO 101
  IF ~~ THEN REPLY #101000 /* ~Move on to the passage opposite the one you entered.~ */ GOTO 116
END

IF ~~ THEN BEGIN 112 // from: 99.2
  SAY #101001 /* ~As you step confidently into the room, the guards struggle to stand up, each giving a drunken approximation of either a bow or a salute. "Itsh about time you gotsh here!" one says. "How long doesh a patrol take?"~ */
  IF ~~ THEN GOTO 113
END

IF ~~ THEN BEGIN 113 // from: 112.0
  SAY #101002 /* ~A second chimes in, "Yeah, you know ol' Lord Fernault wantsh hish gold, and he wantsh it when he wantsh it! Sho you besht getsh goin'— Hey, wait a minute. Didn't the patrol get back an hour ago?" The group nods, and the drunkard points at you. "Then who'sh <PRO_HESHE>?" The soldiers quickly draw their weapons, and you are forced to fight.~ */
  IF ~~ THEN GOTO 101
END

IF ~~ THEN BEGIN 114 // from: 99.4
  SAY #101003 /* ~You slip the ring on, step boldly into the room, and head to the opposite exit. The guards are so engrossed in their cards and food fight that they don't even hear your footsteps. Soon, you have put the group behind you and are heading further into the mountain.~ */
  IF ~~ THEN GOTO 116
END

IF ~~ THEN BEGIN 115 // from: 105.1
  SAY #101004 /* ~Really? You run away? What kind of adventure is that, you coward? Time to reconsider.~ */
  IF ~~ THEN REPLY #101005 /* ~Attack the new warrior.~ */ GOTO 106
  IF ~~ THEN REPLY #101006 /* ~Nope. I'm done. I'm going to run away.~ */ GOTO 92
END

IF ~~ THEN BEGIN 116 // from: 85.0 88.0 95.1 96.1 98.0 108.0 111.1 114.0
  SAY #101007 /* ~A short distance later, the passage widens into a room roughly thirty feet square with a recess in the far wall that is covered by heavy iron bars surrounding a crude, locked oaken door. At first, you see only darkness when you peer into the gloom behind the bars, but then the shadows shift and two figures emerge: a middle-aged man with piercing blue eyes and a wild, unkempt beard and a pretty young girl in her teens.~ */
  IF ~~ THEN GOTO 117
END

IF ~~ THEN BEGIN 117 // from: 116.0
  SAY #101008 /* ~The man eyes you warily. "You don't look familiar," he states hesitantly. "Are you with our captors?"~ */
  IF ~~ THEN REPLY #101009 /* ~Answer that you are not.~ */ GOTO 118
  IF ~~ THEN REPLY #101010 /* ~Answer that you are.~ */ GOTO 122
  IF ~~ THEN REPLY #101011 /* ~Ask who they are.~ */ GOTO 118
END

IF ~~ THEN BEGIN 118 // from: 117.0 117.2 122.0
  SAY #101012 /* ~He sighs, "I am Aldaron and this is Peldea, both of the village of Berenford. Peldea is a hostage kept here to ensure her father, a blacksmith, works adequately to supply Lord Fernault's troops with weapons. I came here some days ago hoping to talk the lord into leaving the region, and if he would not see reason, I was prepared to kill him. I am a priest of Lathander, you see, and I thought the Morninglord would protect me, but I was not prepared for what I found here."~ */
  IF ~~ THEN GOTO 119
END

IF ~~ THEN BEGIN 119 // from: 118.0
  SAY #101013 /* ~"I convinced the guards to let me meet Lord Fernault. They laughed, but in the end, they agreed. But when I was led into his chamber, I saw very little of Fernault. It was a huge cavern, and he spoke from the shadows. I pleaded with him to leave, but he gave my request no regard. After a few minutes, he tired of the conversation, and that's when he made his move."~ */
  IF ~~ THEN GOTO 120
END

IF ~~ THEN BEGIN 120 // from: 119.0
  SAY #101014 /* ~"The shadow itself surrounded me. I could barely take it in before I was knocked unconscious. The next thing I knew, I awoke in this cell, and I've been a prisoner ever since. I never got a good look at Lord Fernault, but this I know. He is most definitely not human, nor is he an elf or dwarf or anything else you might expect."~ */
  IF ~~ THEN GOTO 121
END

IF ~~ THEN BEGIN 121 // from: 120.0
  SAY #101015 /* ~"Now, I would beg you to free us, but the key is in Fernault's chamber, and I fear you will have no better luck than I did. However, if you can recover the keys and free me, I shall help you do battle with Lord Fernault if you so choose." You bid the pair farewell and continue on further into the mountain.~ */
  IF ~~ THEN GOTO 123
END

IF ~~ THEN BEGIN 122 // from: 117.1
  SAY #101016 /* ~"A shame." The man shrugs as both prisoners return to the gloom of the cell.~ */
  IF ~~ THEN REPLY #101017 /* ~Admit that you lied and really aren't with their captors.~ */ GOTO 118
  IF ~~ THEN REPLY #101018 /* ~Continue on deeper into the mountain.~ */ GOTO 123
END

IF ~~ THEN BEGIN 123 // from: 121.0 122.1
  SAY #101019 /* ~The passage into the mountain now takes a deep plunge, and the air becomes stifling as the little breeze that once existed stills. After some time, the tunnel gives way to a large cavern dotted by torches that fail to completely illuminate the gloom. A crude throne sits upon a stone dais hewn into the far end, and the cavern is littered with large piles of coins and jewels.~ */
  IF ~~ THEN REPLY #101020 /* ~Enter the cavern cautiously.~ */ GOTO 124
  IF ~~ THEN REPLY #101021 /* ~Enter the cavern boldly.~ */ GOTO 125
  IF ~  Global("OHBN_RING","LOCALS",1)
~ THEN REPLY #101022 /* ~Put on your ring of invisibility and sneak into the cavern.~ */ GOTO 126
END

IF ~~ THEN BEGIN 124 // from: 123.0
  SAY #101023 /* ~You slip into the chamber, keeping your back to the wall, and carefully edge your way around the cavern. The air is now so hot that sweat pours down your face, and you hear nothing except the popping of the flickering torches. Suddenly, a voice rings out in the gloom.~ */
  IF ~~ THEN GOTO 127
END

IF ~~ THEN BEGIN 125 // from: 123.1
  SAY #101024 /* ~You stride confidently into the chamber, coolly surveying the cavern for any signs of movement. The air is now so hot that sweat pours down your face, and you hear nothing except the popping of the flickering torches. Suddenly, a voice rings out in the gloom.~ */
  IF ~~ THEN GOTO 127
END

IF ~~ THEN BEGIN 126 // from: 123.2
  SAY #101025 /* ~You slip on your ring of invisibility and enter the chamber, coolly surveying the cavern for any signs of movement. The air is now so hot that sweat pours down your face, and you hear nothing except the popping of the flickering torches. Suddenly, a voice rings out. "Do you really think such petty magics will fool me? Your attempt at deception would be laughable were it not so insulting!"~ */
  IF ~~ THEN GOTO 127
END

IF ~~ THEN BEGIN 127 // from: 124.0 125.0 126.0
  SAY #101026 /* ~"I see you, puny one," slithers the mellifluous tenor. The voice echoes around the cavern, but you are unable to see any living being through the gloom. "I am curious as to why you have entered the domain of Fernault the Ravager. That you have done so proves you are either very brave... or very stupid."~ */
  IF ~~ THEN REPLY #101027 /* ~Ask that Fernault leave the people here in peace.~ */ GOTO 128
  IF ~~ THEN REPLY #101028 /* ~Demand that Fernault leave the people here in peace.~ */ GOTO 129
  IF ~~ THEN REPLY #101029 /* ~Ask that Fernault free his two prisoners.~ */ GOTO 128
  IF ~~ THEN REPLY #101030 /* ~Demand that Fernault free his two prisoners.~ */ GOTO 129
  IF ~~ THEN REPLY #101031 /* ~State that you are a treasure hunter and are here for the gold and jewels.~ */ GOTO 130
END

IF ~~ THEN BEGIN 128 // from: 127.0 127.2
  SAY #101032 /* ~The voice laughs hollowly. "And what possible reason would I have to do that when everything here is proceeding exactly as I desire it?"~ */
  IF ~~ THEN REPLY #101036 /* ~Threaten the voice with death if it does not give in to your demands~ CORRECTED */ GOTO 131
  IF ~~ THEN REPLY #101037 /* ~Offer gold if the voice will give in to your demands.~ CORRECTED */ GOTO 132
END

IF ~~ THEN BEGIN 129 // from: 127.1 127.3
  SAY #101035 /* ~The voice sneers, "You are in no position to make demands of me, maggot! It is MY word that is law here, not yours!"~ */
  IF ~~ THEN REPLY #101036 /* ~Threaten the voice with death if it does not give in to your demands.~ */ GOTO 131
  IF ~~ THEN REPLY #101037 /* ~Offer gold if the voice will give in to your demands.~ */ GOTO 132
END

IF ~~ THEN BEGIN 130 // from: 127.4
  SAY #101038 /* ~The voice sneers, "Then the explanation is that you are stupid and not brave. To make such an admission shows that you value your life very little."~ */
  IF ~~ THEN GOTO 134
END

IF ~~ THEN BEGIN 131 // from: 128.0 129.0 132.0 133.0
  SAY #101039 /* ~"Death? YOU think to cause MY death? So very foolish. But at least you are right in sensing that this conversation is bound to lead nowhere but violence."~ */
  IF ~~ THEN GOTO 134
END

IF ~~ THEN BEGIN 132 // from: 128.1 129.1
  SAY #101040 /* ~"I smell gold as easily as you insignificant worms smell a roast on a flame, and you do not have enough gold to buy any favor from me, no matter how insignificant. And even if you did, I would simply kill you and take it. Now I have lost interest in you, but I will allow you to go in peace if you leave at once."~ */
  IF ~~ THEN REPLY #101041 /* ~Threaten the voice with death if it does not give in to your demands.~ */ GOTO 131
  IF ~~ THEN REPLY #101042 /* ~Leave Mount Redigar and abandon the quest.~ */ GOTO 133
END

IF ~~ THEN BEGIN 133 // from: 132.1
  SAY #101043 /* ~Really? You abandon the quest? What kind of adventure is that, you coward? Time to reconsider.~ */
  IF ~~ THEN REPLY #101044 /* ~Threaten the voice with death if it does not give in to your demands.~ */ GOTO 131
END

IF ~~ THEN BEGIN 134 // from: 130.0 131.0
  SAY #101046 /* ~The very shadows begin to shift and coalesce into a frightening figure—tall, muscular, and bulky—that stands up, filling the cavern. Two expansive wings explode outwards and a pair of massive paws bearing a bevy of two-foot-long talons scrape down upon the floor a few feet in front of you. The entire figure is coated in thick scales, a seemingly impenetrable armor dark maroon in color.~ */
  IF ~~ THEN GOTO 135
END

IF ~~ THEN BEGIN 135 // from: 134.0
  SAY #101047 /* ~Two yellow orbs fly open above you and are soon joined by hissing fangs and smoking nostrils. "You wanted Fernault the Ravager?" the beast asks in the same lilting tenor that seems strangely light considering its girth. "Well, now you've got Fernault the Ravager!"~ */
  IF ~ !Global("OHBN_HELMET","LOCALS",1)
RandomNumLT(6,5)
~ THEN GOTO 138
  IF ~ !Global("OHBN_HELMET","LOCALS",1)
RandomNumGT(6,4)
~ THEN GOTO 137
  IF ~  Global("OHBN_HELMET","LOCALS",1)
~ THEN GOTO 136
END

IF ~~ THEN BEGIN 136 // from: 135.2
  SAY #101048 /* ~The sight of the massive dragon is overwhelming, and you feel the slightest hint of fear in the pit of your stomach, but you are soon awash in a calm that seems almost supernatural. That you can look such a beast in the face with no emotion is curious, but you have little time to think on it further as you draw your sword and face it.~ */
  IF ~~ THEN GOTO 142
END

IF ~~ THEN BEGIN 137 // from: 135.1
  SAY #101049 /* ~The sight of the massive dragon is overwhelming, and fear begins to well up in you uncontrollably. You turn to flee, but the moment you sever your gaze from the creature, the fear dissipates to a controllable level. You have little time to think on it further as you draw your sword and turn to face the creature.~ */
  IF ~~ THEN GOTO 142
END

IF ~~ THEN BEGIN 138 // from: 135.0
  SAY #101050 /* ~The sight of the massive dragon is overwhelming, and fear wells up in you uncontrollably. You flee from the chamber, all thoughts other than escape of no concern. You vaguely hear the dragon laughing and jeering you as you flee, but any consideration of pride is far from your mind.~ */
  IF ~~ THEN GOTO 139
END

IF ~~ THEN BEGIN 139 // from: 138.0
  SAY #101051 /* ~After an indeterminate time, a sense of calm overcomes you, and you look around to find yourself in the prison room where you met the middle-aged man and the young girl. The man sees your confusion. "Dragon fear," he states matter-of-factly. "Nothing you can do, but I was able to calm you through the divine powers Lathander grants me. You should now be able to face Fernault without any further fear... at least of the supernatural variety."~ */
  IF ~~ THEN REPLY #101052 /* ~Return to the cavern.~ */ GOTO 140
  IF ~~ THEN REPLY #101053 /* ~Leave Mount Redigar and abandon the quest.~ */ GOTO 141
END

IF ~~ THEN BEGIN 140 // from: 139.0 141.0
  SAY #101054 /* ~You thank the priest and return to the cavern. The dragon immediately spies you and eyes you curiously, one eye cocked. "How is it that you return so soon? Ah," it sniggers, "the Lathanderite. I knew I should have killed him, but by restoring your courage, at least he has granted me the pleasure of rending you apart!"~ */
  IF ~~ THEN GOTO 142
END

IF ~~ THEN BEGIN 141 // from: 139.1
  SAY #101055 /* ~Really? You abandon the quest? What kind of adventure is that, you coward? Time to reconsider.~ */
  IF ~~ THEN REPLY #101056 /* ~Return to the cavern and face the dragon.~ */ GOTO 140
  IF ~~ THEN REPLY #101057 /* ~Nope. I'm done. I'm going to run away.~ */ GOTO 92
END

IF ~~ THEN BEGIN 142 // from: 136.0 137.0 140.0
  SAY #101058 /* ~The fanged jaws open and begin to inhale air in such volume that you fear you might be sucked up into them. Looking deep into the beast's throat, you see the air intake is acting as a bellows within the creature's gut. The great furnace within is even now building a large flame that erupts into the creature's throat, and you realize with dread that the air that is getting sucked in must also eventually be blown out. You dive back into the narrow passage, hoping the walls will protect you from the inferno about to be unleashed.~ */
  IF ~ !Global("OHBN_CLOAK","LOCALS",1)
RandomNumLT(6,5)
~ THEN GOTO 145
  IF ~ !Global("OHBN_CLOAK","LOCALS",1)
RandomNumGT(6,4)
~ THEN GOTO 144
  IF ~  Global("OHBN_CLOAK","LOCALS",1)
~ THEN GOTO 143
END

IF ~~ THEN BEGIN 143 // from: 142.2
  SAY #101059 /* ~The flames envelop you completely, and you know you must be burned alive, yet you remain amazingly unaffected. In fact, you view the flames around you curiously—almost academically—as they curl around you, hungrily licking your hands, face, and body while doing absolutely no harm to you. Eventually, the flames relent, and you turn around in the soot-blackened tunnel.~ */
  IF ~~ THEN GOTO 146
END

IF ~~ THEN BEGIN 144 // from: 142.1
  SAY #101060 /* ~You slam yourself to the ground and roll into a depression that shields you as the flames roar by overhead. The oxygen is burned away, starving your lungs and suffocating you as you feel the hair on your neck and head singeing. You gasp for air and endure the overwhelming burning on your back for what seems like an eternity, but eventually the flames relent, and you roll over gasping in the soot-blackened tunnel.~ */
  IF ~~ THEN GOTO 147
END

IF ~~ THEN BEGIN 145 // from: 142.0
  SAY #101061 /* ~You slam yourself to the ground hoping to find any cover that might shield you from the flames, but it is too late. The oxygen is burned away, starving your lungs and suffocating you as your body is engulfed in the searing heat. It doesn't take long for you to lose consciousness, never to awaken again.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 146 // from: 143.0
  SAY #101062 /* ~You see a large reptilian eye peering up the tunnel at you. "Ahh..." the dragon exclaims as the eye widens in understanding. "The cloak you wear is enchanted with flame resistance. Very clever, mortal, but my talons and fangs are still more than enough. Come back out here and face me!"~ */
  IF ~~ THEN REPLY #101063 /* ~Return to the cavern and face the dragon.~ */ GOTO 149
  IF ~~ THEN REPLY #101064 /* ~Leave Mount Redigar and abandon the quest.~ */ GOTO 148
END

IF ~~ THEN BEGIN 147 // from: 144.0
  SAY #101065 /* ~You see a large reptilian eye peering up the tunnel at you. "Incredible that you survived that, mortal," the dragon exclaims as the eye widens in amazement, "but my talons and fangs are still more than enough. Come back out here and face me!"~ */
  IF ~~ THEN REPLY #101066 /* ~Return to the cavern and face the dragon.~ */ GOTO 149
  IF ~~ THEN REPLY #101067 /* ~Leave Mount Redigar and abandon the quest.~ */ GOTO 148
END

IF ~~ THEN BEGIN 148 // from: 146.1 147.1
  SAY #101068 /* ~Really? You abandon the quest? What kind of adventure is that, you coward? Time to reconsider.~ */
  IF ~~ THEN REPLY #101069 /* ~Return to the cavern and face the dragon.~ */ GOTO 149
  IF ~~ THEN REPLY #101070 /* ~Nope. I'm done. I'm going to run away.~ */ GOTO 92
END

IF ~~ THEN BEGIN 149 // from: 146.0 147.0 148.0
  SAY #101071 /* ~You return to the cavern, sword in hand, to find the dragon eying you with what might be described—remotely—as respect. "No fear, no flames," it mutters. "Looks like we'll have to do this the old-fashioned way!" Without any further warning, it swipes a massive talon towards you!~ */
  IF ~ Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 151
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 150
END

IF ~~ THEN BEGIN 150 // from: 149.2 151.2 153.2 155.2
  SAY #101072 /* ~You dodge the massive paw with an acrobatic roll and come up, sword swinging. You connect, severing one of the dragon's talons. The beast howls in rage and pushes upwards, wings outstretched into the gloom, but a telltale thud followed by collapsing rock reveals that the monster's mobility is severely restricted in what for it is a small space.~ */
  IF ~~ THEN GOTO 157
END

IF ~~ THEN BEGIN 151 // from: 149.1 151.1 153.1 155.1
  SAY #101073 /* ~The claws slam into you, knocking you forcefully to the ground, but you are able to position your body such that the subsequent rolling launches you back on your feet, sword still in hand. The beast howls in triumph and swipes at you again.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101074 /* ~Try to dodge and parry the claws again.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101074 /* ~Try to dodge and parry the claws again.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 151
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101074 /* ~Try to dodge and parry the claws again.~ */ GOTO 150
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101075 /* ~Take cover in the hallway.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101075 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 153
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101075 /* ~Take cover in the hallway.~ */ GOTO 152
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101076 /* ~Run towards the stone dais to gain some height.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101076 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 155
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101076 /* ~Run towards the stone dais to gain some height.~ */ GOTO 154
END

IF ~~ THEN BEGIN 152 // from: 151.5 153.5 155.5
  SAY #101077 /* ~You step back into the hallway as the claw scratches and pushes its way into the opening, grasping for you. You swing your sword at the paw and connect, severing one of the dragon's talons. The beast howls in rage as it withdraws its battered hand and pushes upwards, wings outstretched into the gloom, but a telltale thud followed by collapsing rock reveals that the monster's mobility is severely restricted in what for it is a small space. Frustrated, it lunges at the opening again, ripping away the earth with its claws until you are once more exposed.~ */
  IF ~~ THEN GOTO 157
END

IF ~~ THEN BEGIN 153 // from: 151.4 153.4 155.4
  SAY #101078 /* ~You attempt to withdraw into the hallway, but the monster is too quick. It grabs you and flings you easily to the ground like a rag doll. Your instincts kick in, and you are able to regain your feet quickly, sword still in hand. The beast howls in triumph and swipes at you again.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101079 /* ~Try to dodge and parry the claws again.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101079 /* ~Try to dodge and parry the claws again.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 151
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101079 /* ~Try to dodge and parry the claws again.~ */ GOTO 150
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101080 /* ~Take cover in the hallway.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101080 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 153
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101080 /* ~Take cover in the hallway.~ */ GOTO 152
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101081 /* ~Run towards the stone dais to gain some height.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101081 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 155
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101081 /* ~Run towards the stone dais to gain some height.~ */ GOTO 154
END

IF ~~ THEN BEGIN 154 // from: 151.8 153.8 155.8
  SAY #101082 /* ~You gain the first few steps just as the monster rounds on you. You dodge the massive paw with an acrobatic roll and come up, sword swinging. You connect, severing one of the dragon's talons. The beast howls in rage and pushes upwards, wings outstretched into the gloom, but a telltale thud followed by collapsing rock reveals that the monster's mobility is severely restricted in what for it is a small space.~ */
  IF ~~ THEN GOTO 158
END

IF ~~ THEN BEGIN 155 // from: 151.7 153.7 155.7
  SAY #101083 /* ~You sprint for the dais, but the monster is too quick. It grabs you and flings you easily to the ground like a rag doll. Your instincts kick in, and you are able to regain your feet quickly, sword still in hand. The beast howls in triumph and swipes at you again.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101084 /* ~Try to dodge and parry the claws again.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101084 /* ~Try to dodge and parry the claws again.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 151
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101084 /* ~Try to dodge and parry the claws again.~ */ GOTO 150
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101085 /* ~Take cover in the hallway.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101085 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 153
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101085 /* ~Take cover in the hallway.~ */ GOTO 152
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101086 /* ~Run towards the stone dais to gain some height.~ */ GOTO 156
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101086 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 155
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101086 /* ~Run towards the stone dais to gain some height.~ */ GOTO 154
END

IF ~~ THEN BEGIN 156 // from: 149.0 151.0 151.3 151.6 153.0 153.3 153.6 155.0 155.3 155.6
  SAY #101087 /* ~The claws slam into you, and you fly into the cavern wall with a thud. Bones crunch audibly and pain washes over every inch of you. You struggle to move again, but your battered body no longer responds properly. The beast howls in triumph and lunges at you again. Unable to move, you are quickly overwhelmed. The world fades to black, the sight of gnashing fangs the last you see.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 157 // from: 150.0 152.0
  SAY #101088 /* ~Frustrated by his inability to maneuver, Fernault launches at you, this time with fangs bared!~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101089 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101089 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 160
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101089 /* ~Meet its fangs with your sword head-on.~ */ GOTO 159
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101090 /* ~Take cover in the hallway.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101090 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 162
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101090 /* ~Take cover in the hallway.~ */ GOTO 161
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101091 /* ~Run towards the stone dais to gain some height.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101091 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 164
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101091 /* ~Run towards the stone dais to gain some height.~ */ GOTO 163
END

IF ~~ THEN BEGIN 158 // from: 154.0
  SAY #101092 /* ~Frustrated by his inability to maneuver, Fernault launches at you, this time with fangs bared!~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101093 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101093 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 166
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101093 /* ~Meet its fangs with your sword head-on.~ */ GOTO 165
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101094 /* ~Retreat further up the dais.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101094 /* ~Retreat further up the dais.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 168
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101094 /* ~Retreat further up the dais.~ */ GOTO 167
END

IF ~~ THEN BEGIN 159 // from: 157.2 160.2 162.2 164.2
  SAY #101095 /* ~As the fangs reach for you, you drop to the floor, roll under the jaw, and thrust upwards with your sword, piercing through the scales and burying your blade to the hilt. Fernault howls and rears backwards, pulling you up to a standing position as you wrench the blade free from its bleeding jaw. The dragon emits a mighty roar that again shakes debris loose from the ceiling.~ */
  IF ~~ THEN GOTO 170
END

IF ~~ THEN BEGIN 160 // from: 157.1 160.1 162.1 164.1
  SAY #101096 /* ~As the maw hungrily reaches for you, you swing your sword head-on, parrying the razor-sharp fang, but the force of the dragon's lunge pushes you backwards against the cavern wall, knocking the breath from your body. You gasp for air as the creature howls in glee. Sensing your imminent demise, it again lunges at you, fangs bared.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101097 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101097 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 160
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101097 /* ~Meet its fangs with your sword head-on.~ */ GOTO 159
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101098 /* ~Take cover in the hallway.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101098 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 162
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101098 /* ~Take cover in the hallway.~ */ GOTO 161
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101099 /* ~Run towards the stone dais to gain some height.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101099 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 164
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101099 /* ~Run towards the stone dais to gain some height.~ */ GOTO 163
END

IF ~~ THEN BEGIN 161 // from: 157.5 160.5 162.5 164.5
  SAY #101100 /* ~You retreat further into the hallway as the fangs reach for you, the muzzle shoveling away ever greater portions of the tunnel. You drop to the floor, roll under the jaw, and thrust upwards with your sword, piercing through the scales and burying your blade to the hilt. Fernault howls and rears backwards, pulling you clean out of the hallway and back up to a standing position, allowing you to wrench the blade free from its bleeding jaw. The dragon emits a mighty roar that again shakes debris loose from the ceiling.~ */
  IF ~~ THEN GOTO 170
END

IF ~~ THEN BEGIN 162 // from: 157.4 160.4 162.4 164.4
  SAY #101101 /* ~As the maw hungrily reaches for you, you give ground and slip into the tunnel again as the razor-sharp fangs slice harmlessly in front of you. The dragon snorts, knocking you to the ground and then again ruthlessly claws away yet more of the hallway until you are once more exposed. You regain your feet as the creature howls in glee. Sensing your imminent demise, it again lunges at you, fangs bared.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101102 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101102 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 160
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101102 /* ~Meet its fangs with your sword head-on.~ CORRECTED */ GOTO 159
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101103 /* ~Take cover in the hallway.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101103 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 162
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101103 /* ~Take cover in the hallway.~ */ GOTO 161
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101104 /* ~Run towards the stone dais to gain some height.~ CORRECTED */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101104 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 164
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101104 /* ~Run towards the stone dais to gain some height.~ */ GOTO 163
END

IF ~~ THEN BEGIN 163 // from: 157.8 160.8 162.8 164.8
  SAY #101105 /* ~You climb the first several steps by the time Fernault has properly rounded on you. As his maw again comes in for the kill, you drop to the floor and allow yourself to slide back down the steps until you are positioned under the jaw. You thrust upwards with your sword, piercing through the scales and burying your blade to the hilt. Fernault howls and rears backwards, pulling you up to a standing position as you wrench the blade free from its bleeding jaw. The dragon emits a mighty roar that again shakes debris loose from the ceiling.~ */
  IF ~~ THEN GOTO 170
END

IF ~~ THEN BEGIN 164 // from: 157.7 160.7 162.7 164.7
  SAY #101106 /* ~You make a run for the dais but are too slow. The dragon cuts you off, and you desperately parry the razor-sharp fang that pass inches from your face, but the force of the dragon's lunge pushes you backwards against the cavern wall, knocking the breath from your body. You gasp for air as the creature howls in glee. Sensing your imminent demise, it again lunges at you, fangs bared.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101107 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101107 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 160
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101107 /* ~Meet its fangs with your sword head-on.~ */ GOTO 159
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101108 /* ~Take cover in the hallway.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101108 /* ~Take cover in the hallway.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 162
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101108 /* ~Take cover in the hallway.~ */ GOTO 161
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101109 /* ~Run towards the stone dais to gain some height.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101109 /* ~Run towards the stone dais to gain some height.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 164
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101109 /* ~Run towards the stone dais to gain some height.~ */ GOTO 163
END

IF ~~ THEN BEGIN 165 // from: 158.2 166.2 168.2
  SAY #101110 /* ~As the fangs reach for you, you drop to the floor and allow yourself to slide down the steps until you are positioned under the jaw. You thrust upwards with your sword, piercing through the scales and burying your blade to the hilt. Fernault howls and rears backwards, pulling you up to a standing position as you wrench the blade free from its bleeding jaw. The dragon emits a mighty roar that again shakes debris loose from the ceiling.~ */
  IF ~~ THEN GOTO 170
END

IF ~~ THEN BEGIN 166 // from: 158.1 166.1 168.1
  SAY #101111 /* ~As the maw hungrily reaches for you, you swing your sword head-on, parrying the razor-sharp fang, but the force of the dragon's lunge pushes you backwards into the stone steps, knocking the breath from your body. You gasp for air as the creature howls in glee. Sensing your imminent demise, it again lunges at you, fangs bared.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101112 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101112 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 166
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101112 /* ~Meet its fangs with your sword head-on.~ */ GOTO 165
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101113 /* ~Retreat further up the dais.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101113 /* ~Retreat further up the dais.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 168
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101113 /* ~Retreat further up the dais.~ */ GOTO 167
END

IF ~~ THEN BEGIN 167 // from: 158.5 166.5 168.5
  SAY #101114 /* ~You climb almost to the top by the time Fernault has closed the gap between you. As his maw again comes in for the kill, you drop to the floor and allow yourself to slide back down the steps until you are positioned under the jaw. You thrust upwards with your sword, piercing through the scales and burying your blade to the hilt. Fernault howls and rears backwards, pulling you up to a standing position as you wrench the blade free from its bleeding jaw. The dragon emits a mighty roar that again shakes debris loose from the ceiling.~ */
  IF ~~ THEN GOTO 170
END

IF ~~ THEN BEGIN 168 // from: 158.4 166.4 168.4
  SAY #101115 /* ~You give ground, trying to gain still more height, but are too slow. The dragon cuts you off, and you desperately parry the razor-sharp fang that pass inches from your face, but the force of the dragon's lunge pushes you backwards into the stone steps, knocking the breath from your body. You gasp for air as the creature howls in glee. Sensing your imminent demise, it again lunges at you, fangs bared.~ */
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101116 /* ~Meet its fangs with your sword head-on.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101116 /* ~Meet its fangs with your sword head-on.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 166
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101116 /* ~Meet its fangs with your sword head-on.~ */ GOTO 165
  IF ~  Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101117 /* ~Retreat further up the dais.~ */ GOTO 169
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101117 /* ~Retreat further up the dais.~ */ DO ~IncrementGlobal("OHBN_XP","LOCALS",-1)
~ GOTO 168
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN REPLY #101117 /* ~Retreat further up the dais.~ */ GOTO 167
END

IF ~~ THEN BEGIN 169 // from: 157.0 157.3 157.6 158.0 158.3 160.0 160.3 160.6 162.0 162.3 162.6 164.0 164.3 164.6 166.0 166.3 168.0 168.3
  SAY #101118 /* ~You try to roll backwards acrobatically, but you are too slow. The creature's maw closes over you. Bones crunch audibly and pain washes over your body. Unable to move, you quickly succumb to death. The world fades to black, the sight of gnashing fangs the last you see.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 170 // from: 159.0 161.0 165.0 167.0
  SAY #101119 /* ~The creature roars at you, blood trickling from its jaw. "Perhaps you are not so weak as I once imagined," it concedes warily, "but you are still little more than a worm compared to my draconic majesty! It is now time to end this!" Fernault again lunges, this time bringing both of his claws and his mouth to bear.~ */
  IF ~~ THEN GOTO 171
END

IF ~~ THEN BEGIN 171 // from: 163.0 170.0
  SAY #101120 /* ~You realize you cannot dodge or parry all three attacks at once, but you DO see an opportunity. With Fernault intently staring at you and his face lunging in for the kill, you see as in slow-motion his eyes are opened wide and growing ever larger in your view. A well-placed strike would pierce his brain and kill him. With no other options, you hurl your sword haft over blade like a giant knife right at the creature's eye...~ */
  IF ~ Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 179
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN DO ~IncrementGlobal("OHBN_XP","GLOBAL",-1)
~ GOTO 173
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 172
END

IF ~~ THEN BEGIN 172 // from: 171.2 173.2
  SAY #101121 /* ~...Your blade sails true! Fernault rears back, roaring furiously as he claws at his empty eye socket. He thrashes around the room, careening wildly into the walls and roof, sending an ever larger cascade of rocks from above. You realize that it is only a matter of time before Mount Redigar collapses in on itself, and you flee back down the hallway you came from.~ */
  IF ~~ THEN GOTO 174
END

IF ~~ THEN BEGIN 173 // from: 171.1 173.1
  SAY #101122 /* ~...Fernault diverts one of his massive paws to swipe the blade from the air, sending it clattering harmlessly against the wall. "What a useless gesture!" he grunts dismissively as you roll under his other paw and retrieve your weapon. The dragon again rounds on you, coming in for the kill, but it seems the gods have given you another chance at victory. You again hurl your sword haft over blade towards the dragon's eye...~ */
  IF ~ Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 179
  IF ~  !Global("OHBN_XP","LOCALS",0)
RandomNumLT(6,6)
OR(2)
RandomNumLT(6,5)
!Global("OHBN_BLADE","LOCALS",1)
~ THEN DO ~IncrementGlobal("OHBN_XP","GLOBAL",-1)
~ GOTO 173
  IF ~  RandomNumGT(6,4)
OR(2)
RandomNumGT(6,5)
Global("OHBN_BLADE","LOCALS",1)
~ THEN GOTO 172
END

IF ~~ THEN BEGIN 174 // from: 172.0
  SAY #101123 /* ~As you pass the prison cells, you see that the collapsing mountain has bent the bars such that the door has torn open. The man is ushering the young girl onwards, and the three of you flee up the ramp towards the sunlight beyond, the corridor collapsing perilously close to your heels as you run. At last, you burst into the open air amidst a cloud of dust and the deafening roar of a rockslide.~ */
  IF ~~ THEN GOTO 175
END

IF ~~ THEN BEGIN 175 // from: 174.0
  SAY #101124 /* ~You keep running until you are well away from the mountain. At last, you turn to see only a pile of rubble where once Mount Redigar stood. You know that Fernault is dead, for not even a dragon can survive a mountain collapsing on top of it, and without Fernault, his forces will scatter to the four winds.~ */
  IF ~~ THEN GOTO 176
END

IF ~~ THEN BEGIN 176 // from: 175.0
  SAY #101125 /* ~You are a hero upon your return to Berenford, and you are forever known as the slayer of Fernault the Ravager. The people love you and elect you mayor and high defender, both posts you are sure you could keep for life, if you so desire.~ */
  IF ~~ THEN GOTO 177
END

IF ~~ THEN BEGIN 177 // from: 176.0
  SAY #101126 /* ~The villagers send multiple expeditions to the ruined mountain, and over time they collect a large amount of coins and jewels, much of which they willingly give to you. They even find your sword, still buried to the hilt in the dragon's decaying skull, and the weapon's fame lives on long after even you have turned to dust.~ */
  IF ~~ THEN GOTO 178
END

IF ~~ THEN BEGIN 178 // from: 177.0
  SAY #101127 /* ~And so our story comes to an end. You have everything you could want: fame, wealth, and power. What you do with them is a story for another time.~ */
  IF ~~ THEN GOTO 322
END

IF ~~ THEN BEGIN 179 // from: 171.0 173.0
  SAY #101128 /* ~...Your aim proves faulty as the sword sails cleanly over the dragon's head and clatters noisily in the darkness beyond. But it matters not for you anymore, as the dragon's claws forcefully knock you to the ground. Helpless to move, the sight of gnashing fangs is the last one you see in this life.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 180 // from: 8.0 327.1
  SAY #101290 /* ~Ooh, a wizard! I always wanted to be a wizard too, even got hold of a magic wand once, but I had to give it back after I turned the local priest's head into a rabbit. Not a rabbit head, mind you, a whole rabbit. Going to the temple was never quite the same after that.~ */
  IF ~~ THEN GOTO 181
END

IF ~~ THEN BEGIN 181 // from: 180.0
  SAY #101291 /* ~Anyway, let me just get my Tome of Adventure here... okay, got it. Let's get started.~ */
  IF ~~ THEN GOTO 182
END

IF ~~ THEN BEGIN 182 // from: 181.0
  SAY #101292 /* ~It is a dark and stormy newt, and you have just... wait. Night. It was a dark and stormy night. Sorry about that. Spilled some tea on the page there. Let's start again.~ */
  IF ~~ THEN GOTO 183
END

IF ~~ THEN BEGIN 183 // from: 182.0
  SAY #101293 /* ~It is a dark and stormy night, and you have just arrived at the place you are to meet your mentor. The Wagon's End is a tavern bright and warm, a beacon of refuge in the unseasonably cold gale that has borne down upon the small country village. You make your way through the deep mud of the road and pound heavily on the barred door.~ */
  IF ~~ THEN GOTO 184
END

IF ~~ THEN BEGIN 184 // from: 183.0
  SAY #101294 /* ~A small window cut in the door slides open and a critical eye examines you face. After a moment, the window slides shut and the door is opened. A hunched man pulls you in quickly and then closes and bars the door just as rapidly.~ */
  IF ~~ THEN GOTO 185
END

IF ~~ THEN BEGIN 185 // from: 184.0
  SAY #101295 /* ~He addresses you. "What in the name of all the Hells has possessed you to walk the roads of Marynford at this late hour? Do you care nothing for your life? Well, you are safe indoors now, and I recommend you stay that way until the next day's dawning."~ */
  IF ~~ THEN GOTO 186
END

IF ~~ THEN BEGIN 186 // from: 185.0
  SAY #101296 /* ~After his scolding, the man shuffles back behind the bar and disappears through a door, muttering to himself about "the young people of today." You look around the room and are disturbed and surprised to note that your mentor is nowhere to be seen. There is one patron eating at the bar.~ */
  IF ~~ THEN REPLY #101297 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101298 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101299 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101300 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 187 // from: 196.0
  SAY #101694 /* ~As you reenter the tavern, the barman affixes you with a cold, one-eyed stare. "Well, ye in or out?" ~ */
  IF ~~ THEN REPLY #101297 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101298 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101299 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101300 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 188 // from: 186.0 187.0 192.2 193.1 194.1 199.0
  SAY #101301 /* ~As you sit down, the patron fixes his one good eye upon you, the other an opaque milky orb. "Bad place for travelin' at night. Ain't ye never heard of the curse? Ain't ye never heard of the tales? 'Tis only a fool's luck that ye even made it to the Wagon's End. By all rights, ye should be dead or worse."~ */
  IF ~~ THEN REPLY #101302 /* ~Ask the man why the village is so dangerous at night.~ */ GOTO 189
  IF ~~ THEN REPLY #101303 /* ~Ask the man if he has seen your mentor.~ */ GOTO 190
  IF ~~ THEN REPLY #101304 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101305 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101306 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 189 // from: 188.0 190.0
  SAY #101307 /* ~The man looks incredulously at you. "Ye daft, are ye? Ain't ye never heard of the curse? 'Tis the curse what makes travelin' the roads so treacherous. 'Tis the curse what makes good folk bar their doors and keep lamps lit all the night long." The man turns back to his dinner and says no more to you.~ */
  IF ~~ THEN REPLY #101308 /* ~Ask the man if he has seen your mentor.~ */ GOTO 190
  IF ~~ THEN REPLY #101309 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101310 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101311 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 190 // from: 188.1 189.0
  SAY #101312 /* ~"Mentor, eh? Is he wearin' a cloak like yourself? He is, is he? Can't say I've seen him. Been here most of the day shelterin' from the gale, and I ain't seen nobody."~ */
  IF ~~ THEN REPLY #101313 /* ~Ask the man why the village is so dangerous at night.~ */ GOTO 189
  IF ~~ THEN REPLY #101314 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101315 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101316 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 191 // from: 186.1 187.1 188.2 189.1 190.1 199.1
  SAY #101317 /* ~As you pass through the door behind the old man, a loose floorboard creaks beneath your weight. The old man starts, upsetting a plate of potatoes and knocking several on the floor. He turns to you with a look of terror that turns to relief followed by indignation upon recognizing you.~ */
  IF ~~ THEN GOTO 192
END

IF ~~ THEN BEGIN 192 // from: 191.0
  SAY #101318 /* ~"By the Hells, I thought it had come for me! What's the matter with you, sneaking up behind good folk at this hour of night? Nearly gave me my death's fright, you did. Thought the terror had come for me, sure as my pap's grave." The man bends to clean up the potatoes, muttering to himself.~ */
  IF ~~ THEN REPLY #101319 /* ~Ask the man if he has seen your mentor.~ */ GOTO 193
  IF ~~ THEN REPLY #101320 /* ~Ask the man what he means by "the terror."~ */ GOTO 194
  IF ~~ THEN REPLY #101321 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101322 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101323 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 193 // from: 192.0 194.0
  SAY #101324 /* ~"Haven't seen anyone but yourself and One-Eye Joe all day. You must have seen Joe eating at the bar as you came back here. Come to think of it, I did hear Essie Dawlins talking about a stranger in town dressed in a cloak. Maybe that's the feller you're looking for."~ */
  IF ~~ THEN REPLY #101325 /* ~Ask the man what he means by "the terror."~ */ GOTO 194
  IF ~~ THEN REPLY #101326 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101327 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101328 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 194 // from: 192.1 193.0
  SAY #101329 /* ~"Never heard of the Terror of Marynford? You really are new here, ain't ye? I'll not say much, as it's a bad omen to speak of such things after sundown, but I will tell ye that this town and the surrounding countryside carry a dark curse. Good folk don't venture outside at night, and those who do disappear." The man returns to cleaning the potatoes.~ */
  IF ~~ THEN REPLY #101330 /* ~Ask the man if he has seen your mentor.~ */ GOTO 193
  IF ~~ THEN REPLY #101331 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101332 /* ~Go outside and look for your mentor around the back of the inn.~ */ GOTO 195
  IF ~~ THEN REPLY #101333 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 195 // from: 186.2 187.2 188.3 189.2 190.2 192.3 193.2 194.2
  SAY #101334 /* ~The wind clutches at your cloak and the rain blurs your vision as you step back outside. You make your way slowly in the darkness toward the back of the inn, stumbling over the rotting remains of ruined oaken kegs as you proceed.~ */
  IF ~~ THEN GOTO 196
END

IF ~~ THEN BEGIN 196 // from: 195.0
  SAY #101335 /* ~You find nothing of note in the back of the inn aside from a mutt, cowering in an overturned crate with a hole cut in one side. You turn to reenter the tavern when something catches your eye. In the distance, you see a shadow silhouetted by the intermittent flashes of lightning.~ */
  IF ~~ THEN REPLY #101336 /* ~Return to the interior of the tavern.~ */ GOTO 187
  IF ~~ THEN REPLY #101337 /* ~Follow the shadow.~ */ GOTO 197
  IF ~~ THEN REPLY #101338 /* ~Stay where you are and watch.~ */ GOTO 198
END

IF ~~ THEN BEGIN 197 // from: 196.1
  SAY #101339 /* ~You move quickly in the direction of the shadow and are able to catch several more fleeting glimpses of it before losing sight of it entirely. You realize that in your haste you have become lost, and it is half an hour before you find the inn again.~ */
  IF ~~ THEN GOTO 199
END

IF ~~ THEN BEGIN 198 // from: 196.2
  SAY #101340 /* ~You squint into the darkness for half an hour but catch no sight of the fleeting shadow again. Finally, shivering and soaked, you make your way back to the inn. As you approach the front porch, the air grows frigid around you and you hear footsteps approaching.~ */
  IF ~~ THEN GOTO 199
END

IF ~~ THEN BEGIN 199 // from: 197.0 198.0
  SAY #101341 /* ~"Get indoors, ye fool! Now!" The old man grabs you and pulls you indoors, barring the door behind you. Seconds after the door is barred, there is a horrible shriek and a beating on the door. The bar is solid and the door holds, and soon the beating and shrieking stop. The old man disappears through a door behind the bar.~ */
  IF ~~ THEN REPLY #101342 /* ~Talk to the patron at the bar.~ */ GOTO 188
  IF ~~ THEN REPLY #101343 /* ~Follow the old man through the door behind the bar.~ */ GOTO 191
  IF ~~ THEN REPLY #101344 /* ~Request a room for the evening and go to sleep.~ */ GOTO 200
END

IF ~~ THEN BEGIN 200 // from: 186.3 187.3 188.4 189.3 190.3 192.4 193.3 194.3 199.2
  SAY #101345 /* ~The old man hands you a rusted key and directs you to the stairs on the left side of the bar. You ascend, and the aged wood creaks in protest at your weight. The room is small, but the bed is soft and warm and you are soon asleep, though your dreams are plagued by a nameless horror.~ */
  IF ~~ THEN GOTO 201
END

IF ~~ THEN BEGIN 201 // from: 200.0
  SAY #101346 /* ~You awake the next day to sunlight filtering through the grimy glass of your bedroom window. Dressing quickly, you descend the creaking stairs to find the common room of the inn deserted. You leave the key on the bar and exit through the main door.~ */
  IF ~~ THEN GOTO 202
END

IF ~~ THEN BEGIN 202 // from: 201.0
  SAY #101347 /* ~The road to town is muddy and damp from the previous night's downpour, and your boots are heavy and soaked when you arrive in the square of the small town of Marynford.~ */
  IF ~~ THEN GOTO 217
END

IF ~~ THEN BEGIN 203 // from: 202.0 217.0
  SAY #101348 /* ~The oaken doors are heavy and solemn as they silently swing closed behind you. An aging man clad in simple robes looks up from the altar to Lathander in the front of the temple. He smiles warmly as he sees you. "Hello, traveler, how may I be of service?"~ */
  IF ~~ THEN REPLY #101349 /* ~Ask the man if he has seen your mentor.~ */ GOTO 204
  IF ~~ THEN REPLY #101350 /* ~Ask the man why the tavern owner bars his door at night.~ */ GOTO 205
  IF ~~ THEN REPLY #101351 /* ~Leave the temple.~ */ GOTO 217
END

IF ~~ THEN BEGIN 204 // from: 203.0 210.0
  SAY #101352 /* ~"You say you are looking for a man clad in robes like yourself? I do believe I noticed someone fitting that description just yesterday. He was speaking to Essie Dawlins at her fruit stand in the town square. You might ask her about him."~ */
  IF ~~ THEN REPLY #101353 /* ~Ask the man why the tavern owner bars his door at night.~ */ GOTO 205
  IF ~~ THEN REPLY #101354 /* ~Leave the temple.~ */ GOTO 217
END

IF ~~ THEN BEGIN 205 // from: 203.1 204.0
  SAY #101355 /* ~The priest's face becomes grave. "It is good you have asked me, if you are not already aware. There is a curse upon Marynford and the surrounding lands. It has been so for years and years. Sadly, the curse originated within these very walls."~ */
  IF ~~ THEN GOTO 206
END

IF ~~ THEN BEGIN 206 // from: 205.0
  SAY #101356 /* ~"My predecessor, a gifted and ambitious priest by the name of Brehan, desired to revive faith in Lathander among the people of Marynford. He preached, devoted his life to service, and offered assistance to all who were in need. Despite these measures, the devotion of the town remained tepid."~ */
  IF ~~ THEN GOTO 207
END

IF ~~ THEN BEGIN 207 // from: 206.0
  SAY #101357 /* ~"Brehan became convinced that a display of power was needed to reveal the glory of Lathander to the villagers, so he undertook an expedition into a nearby ruin to rebuke and destroy a ghost that was rumored to reside there."~ */
  IF ~~ THEN GOTO 208
END

IF ~~ THEN BEGIN 208 // from: 207.0
  SAY #101358 /* ~"He found and destroyed the ghost, but as the ghost faded from existence, it cursed him to eternal undeath. Brehan fell ill and soon became ghostly pale himself and increasingly terrified of the light of day."~ */
  IF ~~ THEN GOTO 209
END

IF ~~ THEN BEGIN 209 // from: 208.0
  SAY #101359 /* ~"One morning, I entered the infirmary and found Brehan's attendant dead on the floor with two puncture wounds on her neck. The door to the temple was battered down, and a set of tracks led in the direction of the ancient ruins. Since then, those who venture out at night sometimes do not return."~ */
  IF ~~ THEN GOTO 210
END

IF ~~ THEN BEGIN 210 // from: 209.0
  SAY #101360 /* ~Here. Take this talisman of Lathander. It may protect you if you run afoul of the beast.~ */
  IF ~~ THEN REPLY #101361 /* ~Ask the man if he has seen your mentor.~ */ DO ~SetGlobal("OHBN_SYMBOL","LOCALS",1)
~ GOTO 204
  IF ~~ THEN REPLY #101362 /* ~Leave the temple.~ */ DO ~SetGlobal("OHBN_SYMBOL","LOCALS",1)
~ GOTO 217
END

IF ~~ THEN BEGIN 211 // from: 217.1
  SAY #101363 /* ~The woman is young and pretty, and she smiles as you approach. "Two robed travelers in as many days. What a coincidence."~ */
  IF ~~ THEN REPLY #101364 /* ~Ask the woman if she has seen your mentor.~ */ GOTO 212
  IF ~~ THEN REPLY #101365 /* ~Ask the woman why the tavern owner bars his doors at night.~ */ GOTO 213
  IF ~~ THEN REPLY #101366 /* ~Leave the woman.~ */ GOTO 217
END

IF ~~ THEN BEGIN 212 // from: 211.0 213.0
  SAY #101367 /* ~"Yes, I have. Wearing a cloak similar to your own. He was buying food for a journey he was taking to the ruins south of town. Oh, I tried to warn him away, but he was resolute. I hope nothing has befallen him."~ */
  IF ~~ THEN REPLY #101368 /* ~Ask the woman why the tavern owner bars his doors at night.~ */ GOTO 213
  IF ~~ THEN REPLY #101369 /* ~Leave the woman.~ */ GOTO 217
END

IF ~~ THEN BEGIN 213 // from: 211.1 212.0
  SAY #101370 /* ~The woman turns pale and clutches the wooden table before her to steady herself. "We... we do not speak of such things. If you must know the answer to your question, ask the priest. He is in the temple. I... I can say no more about it. But take this garlic. It is said that the terror fears garlic."~ */
  IF ~~ THEN REPLY #101371 /* ~Ask the woman if she has seen your mentor.~ */ DO ~SetGlobal("OHBN_GARLIC","LOCALS",1)
~ GOTO 212
  IF ~~ THEN REPLY #101372 /* ~Leave the woman.~ */ DO ~SetGlobal("OHBN_GARLIC","LOCALS",1)~
GOTO 217
END

IF ~~ THEN BEGIN 214 // from: 217.2
  SAY #101373 /* ~"Howdy. I'm Bugs, and this here is Finney. We reckoned you were new around here 'cause we've never seen you before and we know just 'bout everyone in town. What brings you to these parts?"~ */
  IF ~~ THEN REPLY #101374 /* ~Ask the man if he has seen your mentor.~ */ GOTO 215
  IF ~~ THEN REPLY #101375 /* ~Ask the man why the tavern owner bars his door at night.~ */ GOTO 216
  IF ~~ THEN REPLY #101376 /* ~Leave the men.~ */ GOTO 217
END

IF ~~ THEN BEGIN 215 // from: 214.0 216.0
  SAY #101377 /* ~"Hmm... A feller wearin' a robe like yours? Hey, Finney, didn't you say you saw a feller like that talking to Essie Dawlins a few days back? Yeah. Go talk to Essie by her fruit stand. She may know somethin'."~ */
  IF ~~ THEN REPLY #101378 /* ~Ask the man why the tavern owner bars his door at night.~ */ GOTO 216
  IF ~~ THEN REPLY #101379 /* ~Leave the men.~ */ GOTO 217
END

IF ~~ THEN BEGIN 216 // from: 214.1 215.0
  SAY #101380 /* ~"Hush now, <PRO_SIRMAAM>. We don't none of us talk about that out of doors. If you got questions 'bout that, best be asking the priest in the temple." He points to the temple of Lathander on the north side of the square.~ */
  IF ~~ THEN REPLY #101381 /* ~Ask the man if he has seen your mentor.~ */ GOTO 215
  IF ~~ THEN REPLY #101379 /* ~Leave the men.~ */ GOTO 217
END

IF ~~ THEN BEGIN 217 // from: 203.2 204.1 210.1 211.2 212.1 213.1 214.2 215.1
  SAY #101382 /* ~You see a temple of Lathander on the north side of the square, a woman selling fruit to the east, and two young men talking under a tall oak in the center of the square. To the south, a road leads out of town and you think you see what appears to be a ruined tower in the distance.~ */
  IF ~~ THEN REPLY #101383 /* ~Enter the temple.~ */ GOTO 203
  IF ~~ THEN REPLY #101384 /* ~Talk to the woman selling fruit.~ */ GOTO 211
  IF ~~ THEN REPLY #101385 /* ~Talk to the two men.~ */ GOTO 214
  IF ~  !Global("OHBN_BANDIT","LOCALS",1)
~ THEN REPLY #101386 /* ~Follow the road to the south.~ */ DO ~SetGlobal("OHBN_BANDIT","LOCALS",1)
~ GOTO 218
  IF ~  Global("OHBN_BANDIT","LOCALS",1)
~ THEN REPLY #101386 /* ~Follow the road to the south.~ */ GOTO 229
END

IF ~~ THEN BEGIN 218 // from: 217.3 226.0
  SAY #101387 /* ~The south road appears little used, and the grass grows high on either side. You are lost in thought, pondering the fate of your mentor, when a figure leaps from hiding. The man is scarred heavily and points his sword at you. "Your money or your life, fool!"~ */
  IF ~~ THEN REPLY #101388 /* ~Cast Magic Missile at the man.~ */ GOTO 219
  IF ~~ THEN REPLY #101389 /* ~Cast Sleep on the man.~ */ GOTO 221
  IF ~~ THEN REPLY #101390 /* ~Cast Charm Person on the man.~ */ GOTO 222
  IF ~~ THEN REPLY #101391 /* ~Try to flee.~ */ GOTO 224
END

IF ~~ THEN BEGIN 219 // from: 218.0
  SAY #101392 /* ~Arcane power surges through you as you utter the final words of the incantation. The bandit's eyes widen as missiles of magical energy tear through his leather armor and throw him back on the road. He lies very, very still.~ */
  IF ~~ THEN GOTO 220
END

IF ~~ THEN BEGIN 220 // from: 219.0
  SAY #101393 /* ~You search the man's corpse and find a few gold pieces. In his breast pocket where the magic missiles struck him, there appears to have been a letter. You try to read it, but much of it was destroyed by your magic. All you can make out is: "...talisman... Lathander..."~ */
  IF ~~ THEN GOTO 226
END

IF ~~ THEN BEGIN 221 // from: 218.1
  SAY #101394 /* ~As your spell envelops the man, his features soften and he slumps to the road in a limp heap. You search him quickly and find a letter in his breast pocket. One section is of particular interest. It reads: "...procure a talisman of Lathander to protect yourself from the undead creature..."~ */
  IF ~~ THEN GOTO 226
END

IF ~~ THEN BEGIN 222 // from: 218.2
  SAY #101395 /* ~You utter the last line of the incantation, and the man suddenly looks at his sword and chuckles. "Heh. What do I need this for, friend? Now, how may I be of service? Oh I know. I'll warn you of the danger in these parts."~ */
  IF ~~ THEN GOTO 223
END

IF ~~ THEN BEGIN 223 // from: 222.0
  SAY #101396 /* ~"The villagers have somehow awakened an undead fiend, but there is a way to weaken it and drive it away. Simply acquire a talisman of Lathander, and it will not try to attack you. I am on my way to try to procure one this very day. Now, I must be off. Good luck!"~ */
  IF ~~ THEN GOTO 226
END

IF ~~ THEN BEGIN 224 // from: 218.3
  SAY #101397 /* ~You turn and begin to run, but you are no match for the bandit's speed. He overtakes you, and you feel a burning pain in your back, then nothing at all as the ground rushes up to receive your dying body.~ */
  IF ~~ THEN GOTO 225
END

IF ~~ THEN BEGIN 225 // from: 224.0 228.0 234.0 251.0
  SAY #101398 /* ~Oh, too bad. Looks like you have been slain. Better luck next time.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 226 // from: 220.0 221.0 223.0
  SAY #101399 /* ~The bandit defeated, you stand on the lonely road. To the south lies the ancient ruin, and to the north lies the small town square.~ */
  IF ~~ THEN REPLY #101400 /* ~Return to the town square.~ */ GOTO 217
  IF ~~ THEN REPLY #101401 /* ~Proceed south toward the ruin.~ */ GOTO 229
END

IF ~~ THEN BEGIN 227 // from: 229.0
  SAY #101402 /* ~The magical projectiles streak unerringly toward their target and stop the charging skeleton in its tracks. Chunks of bone sail high into the air as it is obliterated.~ */
  IF ~~ THEN GOTO 230
END

IF ~~ THEN BEGIN 228 // from: 229.1 229.2
  SAY #101403 /* ~Your spell leaves your fingers and settles over the undead creature, but it appears to be unaffected. The simple life force within the animated bones is immune to the enchantment. You struggle to begin another spell, but the undead monster is upon you and the ground rushes up to receive your lifeless body.~ */
  IF ~~ THEN GOTO 225
END

IF ~~ THEN BEGIN 229 // from: 217.4 226.1
  SAY #101404 /* ~Eventually, you find yourself staring at crumbling stone walls and a decrepit tower, all that remain of a once-mighty fortress. As soon as you enter the ruined courtyard, a shriek erupts and a skeletal figure charges you!~ */
  IF ~~ THEN REPLY #101405 /* ~Cast Magic Missile at the skeleton.~ */ GOTO 227
  IF ~~ THEN REPLY #101406 /* ~Cast Sleep at the skeleton.~ */ GOTO 228
  IF ~~ THEN REPLY #101407 /* ~Cast Charm person at the skeleton.~ */ GOTO 228
END

IF ~~ THEN BEGIN 230 // from: 227.0 233.0 236.0
  SAY #101408 /* ~The courtyard has a ruined shed to the north which seems to have been visited recently. There is a ruined building to the south which appears undisturbed. There is also a dark doorway to the east which appears to have seen recent activity. Beside the door, you notice a shred of fabric the same color as your mentor's cloak.~ */
  IF ~  !Global("OHBN_MUMMY","LOCALS",1)
~ THEN REPLY #101409 /* ~Enter the ruined shed to the north.~ */ DO ~SetGlobal("OHBN_MUMMY","LOCALS",1)
~ GOTO 231
  IF ~  !Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101410 /* ~Enter the undisturbed building to the south.~ */ DO ~SetGlobal("OHBN_HOLYWATER","LOCALS",1)
~ GOTO 235
  IF ~~ THEN REPLY #101411 /* ~Enter the dark doorway to the east.~ CORRECTED */ GOTO 237
END

IF ~~ THEN BEGIN 231 // from: 230.0
  SAY #101412 /* ~The rotten timber of the shed door gives way to your hand, and the decrepit wood falls to the ground before you, revealing a ghastly, dusty figure wrapped in strips of cloth, shambling forward from the darkness.~ */
  IF ~~ THEN REPLY #101413 /* ~Cast Magic Missile at the mummy.~ */ GOTO 232
  IF ~~ THEN REPLY #101414 /* ~Cast Burning Hands at the mummy.~ */ GOTO 233
  IF ~~ THEN REPLY #101415 /* ~Cast Sleep at the mummy.~ */ GOTO 234
  IF ~~ THEN REPLY #101416 /* ~Cast Charm Person at the mummy.~ */ GOTO 234
END

IF ~~ THEN BEGIN 232 // from: 231.0
  SAY #101417 /* ~The missiles strike the shambling figure and tear great holes in its chest. The creature stumbles to one knee, then slowly regains its footing, allowing you time to begin another spell.~ */
  IF ~~ THEN REPLY #101418 /* ~Cast Burning Hands at the mummy.~ */ GOTO 233
  IF ~~ THEN REPLY #101419 /* ~Cast Sleep at the mummy.~ */ GOTO 234
  IF ~~ THEN REPLY #101420 /* ~Cast Charm Person at the mummy.~ */ GOTO 234
END

IF ~~ THEN BEGIN 233 // from: 231.1 232.0
  SAY #101421 /* ~Flames arc forward from your outstretched hands, and the shambling figure is engulfed in an inferno of bright flames. It falls to the ground and thrashes as it is reduced to ashes. Glancing about the shed reveals nothing of value.~ */
  IF ~~ THEN GOTO 230
END

IF ~~ THEN BEGIN 234 // from: 231.2 231.3 232.1 232.2
  SAY #101422 /* ~Your spell leaves your fingers and settles over the undead creature, but it appears to be unaffected. The simple life force within the dusty wraps is immune to the enchantment. You struggle to begin another spell, but the undead monster is upon you and the ground rushes up to receive your lifeless body.~ */
  IF ~~ THEN GOTO 225
END

IF ~~ THEN BEGIN 235 // from: 230.1
  SAY #101423 /* ~The grass grows high and thick around the undisturbed building, and there are even some delicate flowers here that grow nowhere else in the bleak ruins. The door is untouched by decay and swings in easily at your touch.~ */
  IF ~~ THEN GOTO 236
END

IF ~~ THEN BEGIN 236 // from: 235.0
  SAY #101424 /* ~On the ground before you lies a set of silver armor flanked by a heavy mace and an intricately engraved shield. You note the symbol of Lathander on the breastplate of the armor. On the belt of the armor is a flask of water which glows with a faint holy light. You take the holy water for future use.~ */
  IF ~~ THEN GOTO 230
END

IF ~~ THEN BEGIN 237 // from: 230.2
  SAY #101425 /* ~You step through the dark threshold, and the air chills around you. A piercing shriek echoes in your head as torches on the walls of the ancient crypt flare with an unearthly blue fire. You fall to one knee as you look up and see a pale figure with large fangs. A vampire.~ */
  IF ~~ THEN REPLY #101426 /* ~Cast Magic Missile at the vampire.~ */ GOTO 238
  IF ~~ THEN REPLY #101427 /* ~Cast Burning Hands at the vampire.~ */ GOTO 239
  IF ~~ THEN REPLY #101428 /* ~Cast Sleep at the vampire.~ */ GOTO 240
  IF ~~ THEN REPLY #101429 /* ~Cast Charm Person at the vampire.~ */ GOTO 240
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101430 /* ~Brandish the symbol of Lathander.~ */ GOTO 241
  IF ~  Global("OHBN_GARLIC","LOCALS",1)
~ THEN REPLY #101431 /* ~Smash your clove of garlic and throw it at the vampire.~ */ GOTO 242
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101432 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 243
END

IF ~~ THEN BEGIN 238 // from: 237.0 239.0
  SAY #101433 /* ~The magical projectiles strike the vampire in the chest, but to your amazement and dismay leave only minor scorches on the skin of the undead monster. The creature winces slightly but continues to advance. You have time to prepare another spell.~ */
  IF ~~ THEN REPLY #101434 /* ~Cast Burning Hands at the vampire.~ */ GOTO 239
  IF ~~ THEN REPLY #101435 /* ~Cast Sleep at the vampire.~ */ GOTO 240
  IF ~~ THEN REPLY #101436 /* ~Cast Charm Person at the vampire.~ */ GOTO 240
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101437 /* ~Brandish the symbol of Lathander.~ */ GOTO 241
  IF ~  Global("OHBN_GARLIC","LOCALS",1)
~ THEN REPLY #101438 /* ~Smash your clove of garlic and throw it at the vampire.~ */ GOTO 242
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101439 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 243
END

IF ~~ THEN BEGIN 239 // from: 237.1 238.0
  SAY #101440 /* ~The flames that arc forth from your hand singe the beast's skin and cause it to shield its eyes, but it is otherwise unharmed. The vampire advances slowly, giving you time to prepare another spell.~ */
  IF ~~ THEN REPLY #101441 /* ~Cast Magic Missile at the vampire.~ */ GOTO 238
  IF ~~ THEN REPLY #101442 /* ~Cast Sleep at the vampire.~ */ GOTO 240
  IF ~~ THEN REPLY #101443 /* ~Cast Charm Person at the vampire.~ */ GOTO 240
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101444 /* ~Brandish the symbol of Lathander.~ */ GOTO 241
  IF ~  Global("OHBN_GARLIC","LOCALS",1)
~ THEN REPLY #101445 /* ~Smash your clove of garlic and throw it at the vampire.~ */ GOTO 242
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101446 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 243
END

IF ~~ THEN BEGIN 240 // from: 237.2 237.3 238.1 238.2 239.1 239.2
  SAY #101447 /* ~Your spell leaves your fingers and settles over the vampire. It smiles mockingly as it shrugs off your enchantment. You struggle to begin another spell, but the undead monster is upon you and the ground rushes up to receive your lifeless body.~ */
  IF ~~ THEN GOTO 225
END

IF ~~ THEN BEGIN 241 // from: 237.4 238.3 239.3 240.0
  SAY #101448 /* ~As you hold up the talisman of Lathander, the crypt flares in a bright holy light. The vampire begins to smoke and stumbles back against the far wall quivering and covering its eyes.~ */
  IF ~~ THEN REPLY #101449 /* ~Cast Magic Missile at the vampire.~ */ GOTO 244
  IF ~~ THEN REPLY #101450 /* ~Cast Burning Hands at the vampire.~ */ GOTO 245
  IF ~  Global("OHBN_GARLIC","LOCALS",1)
~ THEN REPLY #101451 /* ~Smash your clove of garlic and throw it at the vampire.~ */ GOTO 246
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101452 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 247
END

IF ~~ THEN BEGIN 242 // from: 237.5 238.4 239.4
  SAY #101453 /* ~As the cloves of garlic strike the vampire, it shudders... with laughter. "You would use garlic against me? You've been deceived by an old wives' tale, you fool!"~ */
  IF ~~ THEN REPLY #101454 /* ~Cast Magic Missile at the vampire.~ */ GOTO 244
  IF ~~ THEN REPLY #101455 /* ~Cast Burning Hands at the vampire.~ */ GOTO 245
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101456 /* ~Brandish the symbol of Lathander.~ */ GOTO 248
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101457 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 247
END

IF ~~ THEN BEGIN 243 // from: 237.6 238.5 239.5
  SAY #101458 /* ~The flask shatters on the stone floor of the crypt, dousing the vampire in holy water. Its flesh begins to smoke and char, and it stumbles against the far wall of the crypt, cowering and shaking.~ */
  IF ~~ THEN REPLY #101459 /* ~Cast Magic Missile at the vampire.~ */ GOTO 244
  IF ~~ THEN REPLY #101460 /* ~Cast Burning Hands at the vampire.~ */ GOTO 245
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101461 /* ~Brandish the symbol of Lathander.~ */ GOTO 248
  IF ~  Global("OHBN_GARLIC","LOCALS",1)
~ THEN REPLY #101462 /* ~Smash your clove of garlic and throw it at the vampire.~ */ GOTO 246
END

IF ~~ THEN BEGIN 244 // from: 241.0 242.0 243.0 246.0
  SAY #101463 /* ~The missiles streak toward the weakened vampire and plow through its flesh, leaving an empty husk in their wake. The vampire slumps to the floor and dissolves into a cloud of gaseous mist which flees the room.~ */
  IF ~~ THEN GOTO 249
END

IF ~~ THEN BEGIN 245 // from: 241.1 242.1 243.1 246.1
  SAY #101464 /* ~The gouts of flame strike the weakened vampire and soon set it ablaze. It shrivels and thrashes, then falls to the floor and slowly dissipates into a cloud of gaseous mist which flees the room.~ */
  IF ~~ THEN GOTO 249
END

IF ~~ THEN BEGIN 246 // from: 241.2
  SAY #101465 /* ~The garlic strikes the weakened vampire—but does not affect it. "Fool!" it hisses. "You've been taken in by that old wives' tale?"~ */
  IF ~~ THEN REPLY #101466 /* ~Cast Magic Missile at the vampire.~ */ GOTO 244
  IF ~~ THEN REPLY #101467 /* ~Cast Burning Hands at the vampire.~ */ GOTO 245
  IF ~  Global("OHBN_SYMBOL","LOCALS",1)
~ THEN REPLY #101468 /* ~Brandish the symbol of Lathander.~ */ GOTO 248
  IF ~  Global("OHBN_HOLYWATER","LOCALS",1)
~ THEN REPLY #101469 /* ~Throw the flask of holy water at the vampire.~ */ GOTO 247
END

IF ~~ THEN BEGIN 247 // from: 241.3 242.3 243.3 246.3
  SAY #101470 /* ~The holy water splashes the weakened vampire, and its flesh curls and chars as blue flames consume it. The vampire collapses on the floor and slowly dissipates into a cloud of gaseous mist which flees the room.~ */
  IF ~~ THEN GOTO 249
END

IF ~~ THEN BEGIN 248 // from: 242.2 243.2 246.2
  SAY #101471 /* ~The holy symbol flares with searing light. Beams of energy pierce the weakened vampire, and its flesh curls and chars as blue flames consume it. The vampire collapses on the floor and slowly dissipates into a cloud of gaseous mist which flees the room.~ */
  IF ~~ THEN GOTO 249
END

IF ~~ THEN BEGIN 249 // from: 244.0 245.0 247.0 248.0
  SAY #101472 /* ~You rush across the crypt to the next door and find your mentor slumped on the floor. Fearing the worst, you check his neck, and he stirs weakly. You realize he is still alive. Beside him is a wooden coffin, and you notice a tendril of gaseous mist escaping into it.~ */
  IF ~~ THEN REPLY #101473 /* ~Take your master and flee the crypt.~ */ GOTO 250
  IF ~~ THEN REPLY #101474 /* ~Cast Burning Hands at the casket.~ */ GOTO 252
END

IF ~~ THEN BEGIN 250 // from: 249.0
  SAY #101475 /* ~You hoist your master over your shoulder and begin the arduous trek back to town. You emerge from the crypt and find that night is fast approaching. You walk as quickly as you can, but with your heavy burden, you are unable to reach the safety of town before nightfall.~ */
  IF ~~ THEN GOTO 251
END

IF ~~ THEN BEGIN 251 // from: 250.0
  SAY #101476 /* ~You become aware of a presence behind you moments before you are struck heavily on your back. You fall to the ground and roll onto your back just as the vampire fastens its fangs to your neck and the world fades to blackness.~ */
  IF ~~ THEN GOTO 225
END

IF ~~ THEN BEGIN 252 // from: 249.1
  SAY #101477 /* ~The wood of the coffin bursts into flame and a shrieking sound reverberates through the crypt as it disintegrates. The shrieking sound subsides, and the crypt is left quiet and lifeless. You shoulder the burden of your mentor and begin the long journey back to town.~ */
  IF ~~ THEN GOTO 253
END

IF ~~ THEN BEGIN 253 // from: 252.0
  SAY #101478 /* ~You arrive in town late at night and find all the doors in town barred. You shout and pound on the doors of the temple of Lathander until a small window above is opened. The priest instantly recognizes you and lets you in.~ */
  IF ~~ THEN GOTO 254
END

IF ~~ THEN BEGIN 254 // from: 253.0
  SAY #101479 /* ~"By the gods! How have you survived out of doors so late? And your friend! He is in need of aid. I shall take him to the infirmary as you tell me your tale."~ */
  IF ~~ THEN GOTO 255
END

IF ~~ THEN BEGIN 255 // from: 254.0
  SAY #101480 /* ~Over the next few days, your mentor regains his health, and the townspeople no longer see the terror stalking at night. They give you what gifts their modest incomes allow and herald you as a hero. When your mentor recovers, you continue your journey together to Waterdeep to pursue your arcane studies there.~ */
  IF ~~ THEN GOTO 256
END

IF ~~ THEN BEGIN 256 // from: 255.0
  SAY #101481 /* ~Wow! That was pretty good. You did it. I guess there isn't any challenge that you cannot overcome. That's a fun game.~ */
  IF ~~ THEN GOTO 322
END

IF ~~ THEN BEGIN 257 // from: 9.0 327.2
  SAY #101482 /* ~Ooh, a thief! That's fun. You know, I once stole something. Yep. It's true. There was a pie pan by the bedroom window of a villager back in Nashkel, and it was completely full. I stole it and took a bite. Turns out it was actually a bed pan. Never really had a taste for pie after that.~ */
  IF ~~ THEN GOTO 258
END

IF ~~ THEN BEGIN 258 // from: 257.0
  SAY #101483 /* ~Yeah, so let me just get my Tome of Adventure and we can begin the game. Okay, here it is. Let's start!~ */
  IF ~~ THEN GOTO 259
END

IF ~~ THEN BEGIN 259 // from: 258.0
  SAY #101484 /* ~You are a professional thief, and a rather talented one at that. You have spent most of your career performing jobs for various trade guilds, mercenary groups, and the occasional noble here and there.~ */
  IF ~~ THEN GOTO 260
END

IF ~~ THEN BEGIN 260 // from: 259.0
  SAY #101485 /* ~Your last job went well, but the noble who hired you cheated you on your payment. In an attempt to recoup your losses, you broke into his personal offices, searching for his safe.~ */
  IF ~~ THEN GOTO 261
END

IF ~~ THEN BEGIN 261 // from: 260.0
  SAY #101486 /* ~Instead, you found a stash of documents which indicated the location of a powerful magical ring owned by a rich merchant in the nearby town of Galenwood. The papers explained that the ring was able to amplify the wearer's natural talents of sneaking and innate dexterity. Apparently, the noble had intentions of stealing the ring for himself.~ */
  IF ~~ THEN GOTO 262
END

IF ~~ THEN BEGIN 262 // from: 261.0
  SAY #101487 /* ~To your astonishment, the documents also hinted that the ring had the ability to turn its wearer invisible as well. The location of the house, and even the location of the safe room in which the ring is kept, were indicated in the documents. You took them and proceeded to the town of Galenwood immediately.~ */
  IF ~~ THEN GOTO 263
END

IF ~~ THEN BEGIN 263 // from: 262.0
  SAY #101488 /* ~The road to Galenwood is heavily wooded, with thick underbrush on either side. Thick tree branches extend across the road just above head level and form a canopy which shields the road from direct sunlight.~ */
  IF ~~ THEN GOTO 264
END

IF ~~ THEN BEGIN 264 // from: 263.0
  SAY #101489 /* ~As you reflect on the beauty of the scene, you hear movement and voices behind you. The voices are distant, but your sharp ears are able to pick up a few words, "...will be rewarded for getting the documents back... thief won't get far..." Looking back, you see nothing and realize you have not been seen yet. You have a few minutes to act.~ */
  IF ~~ THEN REPLY #101490 /* ~Stand in the road and await your pursuers.~ */ GOTO 265
  IF ~~ THEN REPLY #101491 /* ~Set a trap beneath the leaves on the road.~ */ GOTO 271
  IF ~~ THEN REPLY #101492 /* ~Climb into the branches directly above the road.~ */ GOTO 276
END

IF ~~ THEN BEGIN 265 // from: 264.0
  SAY #101493 /* ~In a few minutes, you see two men walk into view. They are clad in chain mail and carry swords and shields. You recognize them as the guards of the noble who cheated you. They stop in surprise at seeing you. Recognition crosses their faces. One shouts, "It's <PRO_HIMHER>!" and they charge at you.~ */
  IF ~~ THEN REPLY #101494 /* ~Stand your ground.~ */ GOTO 266
  IF ~~ THEN REPLY #101495 /* ~Climb into the branches directly above the road.~ */ GOTO 267
  IF ~~ THEN REPLY #101496 /* ~Set a trap beneath the leaves on the road.~ */ GOTO 268
  IF ~~ THEN REPLY #101497 /* ~Slip into the underbrush on the side of the road.~ */ GOTO 269
END

IF ~~ THEN BEGIN 266 // from: 265.0
  SAY #101498 /* ~The guards reach you in a matter of seconds. You parry the thrust of the first guard with your short sword, but the second guard dazes you with a shield block to the face. You stumble backwards and feel a searing pain in your chest. Then the world around you goes black.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 267 // from: 265.1
  SAY #101499 /* ~You leap onto the trunk of a nearby tree and almost make it out of reach, but the guards are too swift. One of them fastens an iron grip around your ankle, and you fall heavily to the ground. The last thing you see is a sword descending toward your exposed throat.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 268 // from: 265.2
  SAY #101500 /* ~Your hands work feverishly but you are still crouched over your trap, setting tools, when the guards reach you. You look up, and the last thing you see is a sword descending toward your exposed neck.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 269 // from: 265.3
  SAY #101501 /* ~You roll fluidly into the underbrush on the side of the road and creep noiselessly forward with practiced stealth. The guards follow you, hacking away at the plant life with their swords.~ */
  IF ~~ THEN GOTO 270
END

IF ~~ THEN BEGIN 270 // from: 269.0
  SAY #101502 /* ~You easily double back and creep up from behind, slipping your short sword through a seam in the trailing guard's armor. Before the other can react, you leap forward and cut his throat, letting him fall silently to the ground. You quickly conceal the bodies and return to the path.~ */
  IF ~~ THEN GOTO 280
END

IF ~~ THEN BEGIN 271 // from: 264.1
  SAY #101503 /* ~You work quickly and methodically, setting up a simple yet effective poison dart trap. You just finish concealing the pressure plate when two men walk into view. They are clad in chain mail and carry swords and shields.~ */
  IF ~~ THEN GOTO 272
END

IF ~~ THEN BEGIN 272 // from: 271.0
  SAY #101504 /* ~You recognize them as the guards of the noble who cheated you. They stop in surprise at seeing you. Recognition crosses their faces. One shouts, "It's <PRO_HIMHER>!" and they charge at you.~ */
  IF ~~ THEN GOTO 273
END

IF ~~ THEN BEGIN 273 // from: 272.0
  SAY #101505 /* ~You retreat several steps and watch in satisfaction as the first of the guards runs right into your trap. Poison darts spring from the brush on either side of the road, piercing the first guard multiple times. He gasps and falls quivering to the ground as the poison takes effect.~ */
  IF ~~ THEN GOTO 274
END

IF ~~ THEN BEGIN 274 // from: 273.0
  SAY #101506 /* ~The second guard is hit once in the flank. He stumbles, and his pace slows, but he continues his attack. Your poison has sapped much of his strength, and you easily parry his attacks and counterattack with successful strikes of your own.~ */
  IF ~~ THEN GOTO 275
END

IF ~~ THEN BEGIN 275 // from: 274.0
  SAY #101507 /* ~In a matter of minutes, the second guard lies dead at your feet, his life's blood staining the road. You quickly conceal the bodies and all signs of the struggle as best you can.~ */
  IF ~~ THEN GOTO 280
END

IF ~~ THEN BEGIN 276 // from: 264.2
  SAY #101508 /* ~You easily make your way into the branches and wait silently. In a few minutes, you see two men walk into view. They are clad in chain mail and carry swords and shields. You recognize them as the guards of the noble who cheated you. They are boasting of their recent exploits with a local barmaid and do not notice you.~ */
  IF ~~ THEN GOTO 277
END

IF ~~ THEN BEGIN 277 // from: 276.0
  SAY #101509 /* ~You wait until they pass, then drop noiselessly behind them, quickly sliding your blade into a weak spot in one of the guard's armor. His lung punctured, he drops noiselessly to the ground.~ */
  IF ~~ THEN GOTO 278
END

IF ~~ THEN BEGIN 278 // from: 277.0
  SAY #101510 /* ~A second later, the second guard notices that his companion is missing and turns, but he is too slow. You lunge at him and bury your short sword in his exposed neck before he can ready his guard. You quickly conceal the bodies and all signs of the struggle as best you can.~ */
  IF ~~ THEN GOTO 280
END

IF ~~ THEN BEGIN 279 // from: 266.0 267.0 268.0 300.0 305.0 312.0 316.0
  SAY #101511 /* ~Oh, too bad! Looks like you lost. Well, it was a fun game anyway. Next time, try to be a little more sneaky.~ */
  IF ~~ THEN GOTO 321
END

IF ~~ THEN BEGIN 280 // from: 270.0 275.0 278.0
  SAY #101512 /* ~Having dealt with the guards, you continue your journey to Galenwood, treading a little more carefully and keeping an ear to the wind and an eye on your back. After a few uneventful hours of travel, you arrive at the gates of the small town and make your way discreetly to the town square.~ */
  IF ~~ THEN GOTO 281
END

IF ~~ THEN BEGIN 281 // from: 280.0 282.2 284.1 287.1 288.2 291.1 294.1 295.2 296.0 297.0 298.3 299.2
  SAY #101513 /* ~You stand in the bustling town square of Galenwood. To the north is a large house which matches the description of the merchant's house in the documents. To the south is a temple of Helm. To the east is a tavern, and beside the tavern is an alley. A man dressed in fine blue clothes can be seen going from the merchant's house to the alley and back, periodically.~ */
  IF ~~ THEN REPLY #101514 /* ~Enter the temple of Helm.~ */ GOTO 282
  IF ~~ THEN REPLY #101515 /* ~Enter the tavern.~ */ GOTO 288
  IF ~~ THEN REPLY #101516 /* ~Follow the finely dressed man to the alley.~ */ GOTO 295
  IF ~~ THEN REPLY #101517 /* ~Approach the merchant's house.~ */ GOTO 298
END

IF ~~ THEN BEGIN 282 // from: 281.0
  SAY #101518 /* ~The interior of the temple is dappled in subtle shades of blue and amber as the sunlight filters in through the ornate stained glass windows of the temple. To your left, several people are praying fervently. At the altar, an acolyte appears to be tending to temple duties.~ */
  IF ~~ THEN REPLY #101519 /* ~Move closer and listen to the prayers.~ */ GOTO 283
  IF ~~ THEN REPLY #101520 /* ~Approach the acolyte.~ */ GOTO 285
  IF ~~ THEN REPLY #101521 /* ~Return outside.~ */ GOTO 281
END

IF ~~ THEN BEGIN 283 // from: 282.0 287.0
  SAY #101522 /* ~You look up and make a show of admiring the intricate carvings on the ceiling as you slowly wander within hearing of the people's prayers. You make out a few words.~ */
  IF ~~ THEN GOTO 284
END

IF ~~ THEN BEGIN 284 // from: 283.0
  SAY #101523 /* ~"...And I pray that you will forgive him for his sins. He is just a simple guard and very handsome. It isn't any fault of his own that the rich merchant's wife fell in love with him and gave him the locket with their names inscribed upon it..." You make note of the information for future use.~ */
  IF ~~ THEN REPLY #101524 /* ~Approach the acolyte.~ */ DO ~SetGlobal("OHBN_AFFAIR","LOCALS",1)
~ GOTO 285
  IF ~~ THEN REPLY #101525 /* ~Return outside.~ */ DO ~SetGlobal("OHBN_AFFAIR","LOCALS",1)
~ GOTO 281
END

IF ~~ THEN BEGIN 285 // from: 282.1 284.0
  SAY #101526 /* ~The young acolyte appears startled as you approach. Your sharp and well-trained eyes see his hands quickly draw back from the temple's offering box. The acolyte follows your gaze, and the expression of horror and surprise on his face tells you he is at your mercy.~ */
  IF ~~ THEN GOTO 286
END

IF ~~ THEN BEGIN 286 // from: 285.0
  SAY #101527 /* ~He begins to speak as his shock subsides. "I... I know things. I know people. I can tell you anything, just... just don't tell the priest! Oh, don't tell Father McNeil!"~ */
  IF ~~ THEN GOTO 287
END

IF ~~ THEN BEGIN 287 // from: 286.0
  SAY #101528 /* ~"The manor house... well... it's owned by Phineas Undergood. He's rich. The richest man in a hundred leagues and more. His steward, Alder Lathel, carries the key to his most prized possession. Alder is always dressed in blue and can be found most days running errands to the tavern."~ */
  IF ~~ THEN REPLY #101529 /* ~Move closer and listen to the prayers.~ */ DO ~SetGlobal("OHBN_KEY","LOCALS",1)
~ GOTO 283
  IF ~~ THEN REPLY #101530 /* ~Return outside.~ */ DO ~SetGlobal("OHBN_KEY","LOCALS",1)
~ GOTO 281
END

IF ~~ THEN BEGIN 288 // from: 281.1
  SAY #101531 /* ~Elegant appointments brighten the interior of this tavern. Several attractive young barmaids are busy serving ale and food to patrons in the crowded common room. In one corner, you see a man in chain mail armor emblazoned with a symbol that you noticed on the large house on the north side of the square.~ */
  IF ~~ THEN REPLY #101532 /* ~Offer to buy a drink for one of the barmaids.~ */ GOTO 289
  IF ~~ THEN REPLY #101533 /* ~Buy a drink for the man in chain mail armor.~ */ GOTO 292
  IF ~~ THEN REPLY #101534 /* ~Return outside.~ */ GOTO 281
END

IF ~~ THEN BEGIN 289 // from: 288.0 294.0
  SAY #101535 /* ~The young girl smiles an enchantingly pretty smile, then speaks with the most hideous voice you have ever heard in your entire life. "Don't mind if I do, love. Me bum's burnin' from all this standin'. Makes me arse twitch, ya know?"~ */
  IF ~~ THEN GOTO 290
END

IF ~~ THEN BEGIN 290 // from: 289.0
  SAY #101536 /* ~The girl sits heavily and downs the entire mug in one swallow, then belches loudly. "Aye, that's good ale. Heh, reminds me of that time when summat else bought me an ale. That guard outside the manor house, ya know? He bought me one to keep me quiet."~ */
  IF ~~ THEN GOTO 291
END

IF ~~ THEN BEGIN 291 // from: 290.0
  SAY #101537 /* ~"Ya see, I was sittin' in the outhouse and heard that good-lookin' guard talkin' to the lady of the manor. Looked out the peephole I did, and saw her give him this locket, had their names engraved on it. When he found out I knew, he bought me drinks to get me fuddled. Didn't work though. Remembered the whole thing."~ */
  IF ~~ THEN REPLY #101538 /* ~Buy a drink for the man in chain mail armor.~ */ DO ~SetGlobal("OHBN_AFFAIR","LOCALS",1)
~ GOTO 292
  IF ~~ THEN REPLY #101539 /* ~Return outside.~ */ DO ~SetGlobal("OHBN_AFFAIR","LOCALS",1)
~ GOTO 281
END

IF ~~ THEN BEGIN 292 // from: 288.1 291.0
  SAY #101540 /* ~The man looks up at you angrily until he sees the flagon of ale in your hand. "Aye, now you're speaking my language. Cheers, mate." He takes the ale and starts drinking. Four flagons later, he starts talking. "Gave my whole life to that heartless wretch, working in his house, guarding his possessions."~ */
  IF ~~ THEN GOTO 293
END

IF ~~ THEN BEGIN 293 // from: 292.0
  SAY #101541 /* ~"Then one day, he up and fires me just to save a few gold coins. I was the one who designed the trap to guard his most prized possession, that damned ring of his. Put it right above the chandelier where nobody'd think to look. Can't believe he fired me."~ */
  IF ~~ THEN GOTO 294
END

IF ~~ THEN BEGIN 294 // from: 293.0
  SAY #101542 /* ~"Got half a mind to steal the ring myself. Since I know about the trap in the chandelier, I only need to get past the guard at the front door and then get the key to the lock and the ring will be mine." The man sways a second after speaking, then falls snoring to the table, spilling the rest of the ale.~ */
  IF ~~ THEN REPLY #101543 /* ~Offer to buy a drink for one of the barmaids.~ */ GOTO 289
  IF ~~ THEN REPLY #101544 /* ~Return outside.~ */ GOTO 281
END

IF ~~ THEN BEGIN 295 // from: 281.2
  SAY #101545 /* ~You wait until the man has his back turned and then slip in the alley behind him. He goes to the back of the tavern and bends over a box, fumbling with the contents. You have a chance to act while his attention is distracted.~ */
  IF ~  Global("OHBN_KEY","LOCALS",1)
~ THEN REPLY #101546 /* ~Attempt to pick his pockets.~ */ DO ~SetGlobal("OHBN_KEY","LOCALS",2)
~ GOTO 296
  IF ~  !Global("OHBN_KEY","LOCALS",1)
~ THEN REPLY #101546 /* ~Attempt to pick his pockets.~ */ GOTO 297
  IF ~~ THEN REPLY #101547 /* ~Return to the town square.~ */ GOTO 281
END

IF ~~ THEN BEGIN 296 // from: 295.0
  SAY #101548 /* ~Your trained hands quickly locate the key in the man's pocket and remove it undetected. You complete the job almost without breaking stride and return to the town square before you attract any attention.~ */
  IF ~~ THEN GOTO 281
END

IF ~~ THEN BEGIN 297 // from: 295.1
  SAY #101549 /* ~You easily slip your hands in the distracted man's various pockets, but are unable to notice anything of value before you must move back to the town square to avoid attracting attention. Perhaps if you knew what you were looking for, you could try again later.~ */
  IF ~~ THEN GOTO 281
END

IF ~~ THEN BEGIN 298 // from: 281.3
  SAY #101550 /* ~You approach the richly decorated house and are promptly halted by a tall and handsome guard at the front door. "Halt. What business do you have with the Undergood Estate?" You realize that if you manage to enter the house, you will not be able to leave and then reenter. You have only one chance once inside.~ */
  IF ~~ THEN REPLY #101551 /* ~Claim to be a safe inspector sent for by the master of the house.~ */ GOTO 299
  IF ~~ THEN REPLY #101552 /* ~Attempt to overpower the guard.~ */ GOTO 300
  IF ~  Global("OHBN_AFFAIR","LOCALS",1)
~ THEN REPLY #101553 /* ~Blackmail the guard with the information about his affair with his master's wife.~ */ GOTO 301
  IF ~~ THEN REPLY #101554 /* ~Return to the town square.~ */ GOTO 281
END

IF ~~ THEN BEGIN 299 // from: 298.0
  SAY #101555 /* ~The guard narrows his eyes for a moment, then enters the house without a word, locking the door behind him. He returns a few moments later with a hard look on his face. "The master's clerk of business knows of no such appointment. Now move along before you find yourself in the stocks."~ */
  IF ~~ THEN REPLY #101556 /* ~Attempt to overpower the guard.~ */ GOTO 300
  IF ~  Global("OHBN_AFFAIR","LOCALS",1)
~ THEN REPLY #101557 /* ~Blackmail the guard with the information about his affair with his master's wife.~ */ GOTO 301
  IF ~~ THEN REPLY #101558 /* ~Return to the town square.~ */ GOTO 281
END

IF ~~ THEN BEGIN 300 // from: 298.1 299.0
  SAY #101559 /* ~You lunge for the guard's throat, but he is ready. His trained muscles quickly overpower you, and you feel a burning pain at your throat as the guard's dagger is drawn quickly across it. The ground rushes up to meet you as the world goes black.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 301 // from: 298.2 299.1
  SAY #101560 /* ~The large man's rugged face pales, and his eyes grow wide. His right hand instinctively clutches at something just below the collar of his tunic. His eyes darting left and right, he silently moves aside, allowing you to pass.~ */
  IF ~~ THEN GOTO 302
END

IF ~~ THEN BEGIN 302 // from: 301.0
  SAY #101561 /* ~You find yourself in the grand entrance of the elegant mansion. Referring to your papers, you find the hallway that leads to the mansion's safe room. It is a long corridor with a painting on the left side, a chandelier hanging from the ceiling, a rug on the floor, and a statue on the right side.~ */
  IF ~~ THEN REPLY #101562 /* ~Proceed to the door of the safe room.~ */ GOTO 303
  IF ~~ THEN REPLY #101563 /* ~Check the painting for a trap.~ */ GOTO 304
  IF ~~ THEN REPLY #101564 /* ~Check the chandelier for a trap.~ */ GOTO 306
  IF ~~ THEN REPLY #101565 /* ~Check the rug for a trap.~ */ GOTO 307
  IF ~~ THEN REPLY #101566 /* ~Check the statue for a trap.~ */ GOTO 308
END

IF ~~ THEN BEGIN 303 // from: 302.0
  SAY #101567 /* ~You stride boldly toward your goal at the end of the corridor. Halfway there, you hear a barely audible twang and feel a sting at the back of your neck.~ */
  IF ~~ THEN GOTO 305
END

IF ~~ THEN BEGIN 304 // from: 302.1
  SAY #101568 /* ~You carefully examine the painting, but find no traces of tripwires, pressure plates, or other conventional triggers. As you step back to think about your next move, you hear a barely audible twang and feel a sting at the back of your neck.~ */
  IF ~~ THEN GOTO 305
END

IF ~~ THEN BEGIN 305 // from: 303.0 304.0 307.0 308.0 310.0
  SAY #101569 /* ~Reaching back, you find a dart protruding from you skin and you realize to your horror that you have triggered a trap. Your vision blurs from the poison dart, and soon your knees buckle. You never feel yourself hit the floor.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 306 // from: 302.2
  SAY #101570 /* ~As you look closely at the chandelier, you see a small network of tiny filaments extending from the ornamental arms of the light fixture to the floor. Where they attach to the chandelier, there are small levers, almost too small to detect.~ */
  IF ~~ THEN GOTO 309
END

IF ~~ THEN BEGIN 307 // from: 302.3
  SAY #101571 /* ~You carefully examine the rug, but find no traces of tripwires, pressure plates, or other conventional triggers. As you step back to think about your next move, you hear a barely audible twang and feel a sting at the back of your neck.~ */
  IF ~~ THEN GOTO 305
END

IF ~~ THEN BEGIN 308 // from: 302.4
  SAY #101572 /* ~You carefully examine the statue, but find no traces of tripwires, pressure plates, or other conventional triggers. As you step back to think about your next move, you hear a barely audible twang and feel a sting at the back of your neck.~ */
  IF ~~ THEN GOTO 305
END

IF ~~ THEN BEGIN 309 // from: 306.0
  SAY #101573 /* ~You carefully avoid the filaments hanging from the chandelier and make your way to the safe room door. It appears to be a normal door with a simple lock below the doorknob.~ */
  IF ~~ THEN REPLY #101574 /* ~Try to pick the lock.~ */ GOTO 310
  IF ~  Global("OHBN_KEY","LOCALS",2)
~ THEN REPLY #101575 /* ~Place the stolen key in the lock and turn it.~ */ GOTO 313
  IF ~~ THEN REPLY @29030 /* ~Try to force the door open.~ */ GOTO 311
END

IF ~~ THEN BEGIN 310 // from: 309.0
  SAY #101576 /* ~You produce your lockpicking tools and begin to work on the lock. The tumblers turn easily beneath your expert fingers, and soon the lock clicks. You stand up triumphantly. Then you hear another click, then a twang. Something strikes the back of your neck.~ */
  IF ~~ THEN GOTO 305
END

IF ~~ THEN BEGIN 311 // from: 
  SAY #101577 /* ~Looking back over your shoulder, you see no one in the corridor. You take a few steps back, then throw your full weight against the door. It gives slightly, then holds solid. Throughout the house, bells sound, and the house fills with the sound of running feet.~ */
  IF ~~ THEN GOTO 312
END

IF ~~ THEN BEGIN 312 // from: 311.0
  SAY #101578 /* ~The corridor fills with guards carrying crossbows, and seconds later the air is full of humming quarrels. The quarrels find their mark, and you drop to your knees. The world fades to blackness.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 313 // from: 309.1
  SAY #101579 /* ~The lock opens silently, and as you open the door, you find that it is comprised of two inches of solid iron. The hinges make no sound whatsoever as you close the door behind you. You turn and survey the room.~ */
  IF ~~ THEN GOTO 314
END

IF ~~ THEN BEGIN 314 // from: 313.0
  SAY #101580 /* ~To your surprise, you see a window overlooking the busy town square. Despite the window, the room seems surprisingly dark, and this strikes you as odd. There is a table with a small stand which holds a simple gold ring. You quickly take the ring and plan your escape.~ */
  IF ~~ THEN REPLY #101581 /* ~Attempt to leave through the strangely dark window.~ */ GOTO 315
  IF ~~ THEN REPLY #101582 /* ~Slip the ring on your finger and exit the way you entered.~ */ GOTO 317
END

IF ~~ THEN BEGIN 315 // from: 314.0
  SAY #101583 /* ~You attempt to open the window, but your hands pass through and push against a metallic plate behind it. As bells sound throughout the house, you realize too late that the window was an illusion.~ */
  IF ~~ THEN GOTO 316
END

IF ~~ THEN BEGIN 316 // from: 315.0
  SAY #101584 /* ~Guards fling the door open and train their crossbows on you. The air hums as their bolts streak toward their target. The quarrels find their mark, and you drop to your knees. The world fades to blackness.~ */
  IF ~~ THEN GOTO 279
END

IF ~~ THEN BEGIN 317 // from: 314.1
  SAY #101585 /* ~You slip the ring on your finger, and the world around you shimmers briefly as the magic cloaks you in invisibility. You exit through the safe room door, taking care to lock it behind you. You return to the grand entry and patiently wait for the door to the square to open.~ */
  IF ~~ THEN GOTO 318
END

IF ~~ THEN BEGIN 318 // from: 317.0
  SAY #101586 /* ~After what seems like an eternity, an elegant middle-aged woman passes through the door with a lingering gaze on the tall guard. You take the opportunity to pass unseen into the square and shortly thereafter out of the city.~ */
  IF ~~ THEN GOTO 319
END

IF ~~ THEN BEGIN 319 // from: 318.0
  SAY #101587 /* ~You travel swiftly for three days until you are certain that you have not been pursued. Only then do you take off the ring and spend the night in a small, nearly deserted tavern. After a surprisingly good dinner, you retire to your room and fall asleep, dreaming of the riches which are sure to be yours.~ */
  IF ~~ THEN GOTO 320
END

IF ~~ THEN BEGIN 320 // from: 319.0
  SAY #101588 /* ~You did it! Well done. Wasn't sure you would make it there toward the end, but you did! Well, that certainly was fun.~ */
  IF ~~ THEN GOTO 322
END

IF ~~ THEN BEGIN 321 // from: 45.0 49.0 52.0 65.0 82.0 86.0 90.0 92.0 93.0 104.0 145.0 156.0 169.0 179.0 225.0 279.0
  SAY #101589 /* ~Oh well, you died, but this has been known to happen in this game. Despite this, was it a fun game?~ */
  IF ~~ THEN REPLY #101590 /* ~Yes, I enjoyed it very much.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 323
  IF ~~ THEN REPLY #101591 /* ~Well, it was a game.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 324
  IF ~~ THEN REPLY #101592 /* ~It wasn't very good, no.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 325
END

IF ~~ THEN BEGIN 322 // from: 178.0 256.0 320.0
  SAY #101593 /* ~So what did you think? Was it a fun game?~ */
  IF ~~ THEN REPLY #101594 /* ~Yes, I enjoyed it very much.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 323
  IF ~~ THEN REPLY #101595 /* ~Well, it was a game.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 324
  IF ~~ THEN REPLY #101596 /* ~It wasn't very good, no.~ */ DO ~SetGlobal("OHBN_XP","LOCALS",0)
SetGlobal("OHBN_KNOWS_FERNAULT","LOCALS",0)
SetGlobal("OHBN_SENESCHAL","LOCALS",0)
SetGlobal("OHBN_HEARTLESS","LOCALS",0)
SetGlobal("OHBN_BLADE","LOCALS",0)
SetGlobal("OHBN_HELMET","LOCALS",0)
SetGlobal("OHBN_CLOAK","LOCALS",0)
SetGlobal("OHBN_RING","LOCALS",0)
SetGlobal("OHBN_BANDIT","LOCALS",0)
SetGlobal("OHBN_SYMBOL","LOCALS",0)
SetGlobal("OHBN_HOLYWATER","LOCALS",0)
SetGlobal("OHBN_GARLIC","LOCALS",0)
SetGlobal("OHBN_KEY","LOCALS",0)
SetGlobal("OHBN_AFFAIR","LOCALS",0)
SetGlobal("j8noober","GLOBAL",3)
~ GOTO 325
END

IF ~~ THEN BEGIN 323 // from: 321.0 322.0
  SAY #101597 /* ~I'm glad to hear it. Would you, by chance, like to play again or perhaps choose another class?~ */
  IF ~~ THEN REPLY #101598 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101599 /* ~No, I would rather quit.~ */ GOTO 326
END

IF ~~ THEN BEGIN 324 // from: 321.1 322.1
  SAY #101600 /* ~Yes, it is definitely a game. Would you, by chance, like to play again or perhaps choose another class?~ */
  IF ~~ THEN REPLY #101601 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101602 /* ~No, I would rather quit.~ */ GOTO 326
END

IF ~~ THEN BEGIN 325 // from: 321.2 322.2
  SAY #101603 /* ~I'm sorry to hear that. Perhaps trying another class would improve your experience. Would you like to try?~ */
  IF ~~ THEN REPLY #101604 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101605 /* ~No, I would rather quit.~ */ GOTO 326
END

IF ~~ THEN BEGIN 326 // from: 323.1 324.1 325.1 327.3
  SAY #101606 /* ~Quit? I can't believe you'd really choose to quit such a fun game. Are you sure?~ */
  IF ~~ THEN REPLY #101607 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101608 /* ~Yes, I am sure.~ */ GOTO 328
END

IF ~~ THEN BEGIN 327 // from: 323.0 324.0 325.0 326.0 328.0 329.0 330.0 331.0 332.0 333.0 334.0
  SAY #101609 /* ~Excellent! Which class would you like: a fighter, a wizard, or a thief?~ */
  IF ~~ THEN REPLY #101610 /* ~I shall take on the role of a fighter.~ */ GOTO 10
  IF ~~ THEN REPLY #101611 /* ~A wizard sounds like it would be fun.~ */ GOTO 180
  IF ~~ THEN REPLY #101612 /* ~I've always enjoyed sneaking around. Let me try being a thief.~ */ GOTO 257
  IF ~~ THEN REPLY #101613 /* ~Eh, I would rather quit after all.~ */ GOTO 326
END

IF ~~ THEN BEGIN 328 // from: 326.1
  SAY #101614 /* ~How about now?~ */
  IF ~~ THEN REPLY #101615 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101616 /* ~Yes, even now.~ */ GOTO 329
END

IF ~~ THEN BEGIN 329 // from: 328.1
  SAY #101617 /* ~What about now?~ */
  IF ~~ THEN REPLY #101618 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101619 /* ~Oh, not this again!~ */ GOTO 330
END

IF ~~ THEN BEGIN 330 // from: 329.1
  SAY #101620 /* ~How about now?~ */
  IF ~~ THEN REPLY #101621 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101622 /* ~This is dumb.~ */ GOTO 331
END

IF ~~ THEN BEGIN 331 // from: 330.1
  SAY #101623 /* ~What about now?~ */
  IF ~~ THEN REPLY #101624 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101625 /* ~Yes, it is STILL dumb.~ */ GOTO 332
END

IF ~~ THEN BEGIN 332 // from: 331.1
  SAY #101626 /* ~How about now?~ */
  IF ~~ THEN REPLY #101627 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101628 /* ~Can we please stop this?~ */ GOTO 333
  IF ~~ THEN REPLY #101629 /* ~I want to kill you so badly. I'm just... it's amazing, really.~ */ GOTO 333
END

IF ~~ THEN BEGIN 333 // from: 332.1 332.2
  SAY #101630 /* ~What about now?~ */
  IF ~~ THEN REPLY #101631 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101632 /* ~Really, just stop.~ */ GOTO 334
  IF ~~ THEN REPLY #101633 /* ~You have no idea how much I loathe you.~ */ GOTO 334
END

IF ~~ THEN BEGIN 334 // from: 333.1 333.2
  SAY #101630 /* ~What about now?~ */
  IF ~~ THEN REPLY #101635 /* ~Okay, perhaps I will try another class.~ */ GOTO 327
  IF ~~ THEN REPLY #101636 /* ~You are the most reprehensible creature in the entire world.~ */ GOTO 335
END

IF ~~ THEN BEGIN 335 // from: 334.1
  SAY #101637 /* ~It appears my time is up, my friend. Goodbye, <CHARNAME>! It has been quite the adventure this past while. Perhaps we shall see each other again some day.~ */
  IF ~~ THEN DO ~GiveItemCreate("jm#shirt",LastTalkedToBy,0,0,0)
ADDXPObject(Player1,3000)
ADDXPObject(Player2,3000)
ADDXPObject(Player3,3000)
ADDXPObject(Player4,3000)
ADDXPObject(Player5,3000)
ADDXPObject(Player6,3000)
EscapeArea()~ EXIT
END
